### ISSUE TITLE
How do we create an upgrade rank?

### ISSUE THREAD

**Issue by Devillion** [WooMinecraft/WooMinecraft#101]
In Buycraft you can set it so they can't upgrade unless they have purchased the required rank first.

Can this be done?

If not this is a major feature as 99% of servers use a ranking system.

**Comment by JayWood** [comment]
Pex has a ranking system, it's built into the permissions plugin.  Utilizing a ladder system one can set the command of a purchase to `pex user %s promote` and depending on the ladder they're on they'll get promoted.

Currently this plugin makes no attempt to handle 'permissions' or 'ranks'.
