### ISSUE TITLE
Multi Server Support

### ISSUE THREAD

**Issue by TheSodaPopPanda** [WooMinecraft/WooMinecraft#103]
I can't seem to find any multi-server support does your plugin have multi-server support 
(if not can you add this or is it to much work)
(if so how would go about setting that up)

**Comment by JayWood** [comment]
This is actually in progress on the dev branch, keep watching :smile:

**Comment by TheSodaPopPanda** [comment]
oh... Nice! how is it coming?

**Comment by JayWood** [comment]
It's super close. Luckily the company I work for is giving us a full day to work on 'personal' projects if we want.  So I'm hoping to get more progress on this tomorrow.

**Comment by JayWood** [comment]
@TheSodaPopPanda - This is what I have so far, now it's a matter of saving the data properly and calling it back in the feed ( when the server requests it ).

![ppsnsm3a9k](https://cloud.githubusercontent.com/assets/2303074/17249908/116c6218-5570-11e6-908e-f95f6e5fc5b5.gif)
Working admin panel options to add/remove servers.

![zk3lbmnrrd](https://cloud.githubusercontent.com/assets/2303074/17249969/519d6490-5570-11e6-95a3-2fb58b1d1434.gif)
Working product panels to set commands to specific servers.

**Comment by TheSodaPopPanda** [comment]
Awesome! looks great can't wait until it's done 
(I really did not want to have to use buycraft)

**Comment by TheSodaPopPanda** [comment]
I should also so.... Thanks! This plugin is really helpful I was really happy when i found it a while back.

**Comment by JayWood** [comment]
You can track dev commits here if interested - https://github.com/WooMinecraft/woominecraft-wp/commits/dev

**Comment by JayWood** [comment]
This is `technically` complete - working on backwards compat fixes now ( migrating old command post meta to new structure ).

Then I have to move to the java side of things to update the 'processedOrders' call to ensure we update orders ONLY by the server key, not just everything.

**Comment by JayWood** [comment]
Backwards compat fixes are in, need to do some java testing, which will have to wait till this weekend since Java isn't WordPress related :smile:

**Comment by TheSodaPopPanda** [comment]
Awesome

**Comment by TheSodaPopPanda** [comment]
I will close the thread but it's been nice to talk you to you

**Comment by JayWood** [comment]
@TheSodaPopPanda You can feel free to try the pre-alpha here - https://github.com/WooMinecraft/woominecraft-wp/archive/dev.zip 

Just make sure you make a backup of the database before you install it. You can use any of the existing jar files in the zip here: https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.0.6

Since all the code is WordPress side, no java update is needed. I've not had time to test it, but I plan to tomorrow night, but if you absolutely want an early release, that's it :smile:
