### ISSUE TITLE
WooMinecraft 1.7.10

### ISSUE THREAD

**Issue by tei06398** [WooMinecraft/WooMinecraft#104]
Is there any chance you could back-port the plugin to 1.7.10?
I would be highly grateful if you would do that.
-tei06398 (Inferno09)

**Comment by JayWood** [comment]
WooMinecraft is in fact available from 1.7 - 1.10.2

I've just not had time to update the github readme :smile:  

You can download it here from spigot - https://www.spigotmc.org/resources/woominecraft.25517/
Or on the releases page here on Github

**Comment by tei06398** [comment]
Thanks! If there are any open positions on the team, I'd be glad to help
out, by the way.

**Comment by JayWood** [comment]
Thanks for the support.  Pull requests to the code base are always welcome :smile:
