### ISSUE TITLE
Error in 1.0.6 

### ISSUE THREAD

**Issue by tei06398** [WooMinecraft/WooMinecraft#106]
After issuing command woo check on the game side, I received this error: [23:45:06 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

**Comment by tei06398** [comment]
UPDATE: Happens when any purchase is marked as complete and received by the server.

**Comment by tei06398** [comment]
Also, isn't it funny how we're talking about 1.0.6 in issue 106?

**Comment by JayWood** [comment]
@tei06398 Understood, I'll work on adding a more verbose error log, ie. showing what was returned. Unfortunately that's kind of vague and I need to know what was returned. Too many possibilities here. Expect an update friday.

**Comment by tei06398** [comment]
@JayWood will this be a WordPress/Plugin update, or just a plugin update?

**Comment by JayWood** [comment]
@tei06398 It will be a Java update ( the java plugin ). Right now it's merely looking at the exception message. I'll update it to pull the full response from the web server instead.

**Comment by Jogib** [comment]
MC version 1.8.8
Java plugin: 1.0.7
WP plugin: 1.0.6

Purchases are not going through :( 
This is the full error i receive when running "/woo check":

29.08 06:42:00 [Server] WARN A JSONObject text must begin with '{' at 1 [character 2 line 1]
29.08 06:42:00 [Server] WARN org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
29.08 06:42:00 [Server] WARN at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
29.08 06:42:00 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:195)
29.08 06:42:00 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:319)
29.08 06:42:00 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:135)
29.08 06:42:00 [Server] WARN at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:59)
29.08 06:42:00 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.08 06:42:00 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
29.08 06:42:00 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
29.08 06:42:00 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
29.08 06:42:00 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
29.08 06:42:00 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
29.08 06:42:00 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
29.08 06:42:00 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
29.08 06:42:00 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by JayWood** [comment]
@Jogib Finally an error, thanks a million! Will jump on this right after work today.

**Comment by JayWood** [comment]
@Jogib would you care to download the latest pre-release? https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.0.8-PRE-1

Set `debug: true` in your config for the plugin, then run this again. It should output the full response from your web server if this same error occurs. Please provide the full log.

**Comment by Jogib** [comment]
@JayWood 
This is the output when running "/woo check" on 1.0.8 and debug: true:
30.08 05:13:35 [Server] WARN Logging an improper server response
30.08 05:13:35 [Server] ERROR /<!doctype html><html lang="en"><head>    <meta content="initial-scale=1.0, width=device-width, user-scalable=yes" name="viewport">    <meta content="yes" name="apple-mobile-web-app-capable">    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <meta name="language" content="en" />    <link rev="made" href="mailto:info@multicraft.org">    <meta name="description" content="Multicraft: The Minecraft server control panel">    <meta name="keywords" content="Multicraft, Minecraft, server, management, control panel, hosting">    <meta name="author" content="xhost.ch GmbH">    <meta charset="UTF-8" />    <link rel="shortcut icon" href="/favicon.ico" />    <link rel="stylesheet" type="text/css" href="/themes/default/css/style.css" media="screen, projection" />    <meta http-equiv="X-FRAME-OPTIONS" content="SAMEORIGIN" /><script type="text/javascript" src="/assets/2897400d/jquery.min.js"></script><script type="text/javascript" src="/assets/2897400d/jquery.yii.js"></script><script type="text/javascript" src="/themes/default/js/theme.js"></script><title>Multicraft - Home</title></head><body><div id="page">    <div id="watermark-logo"></div>    <div id="mini">                        <div class="row" id="header">            <div id="logo">                <h1>Multicraft<small>Minecraft Server Manager</small></h1>            </div>        </div>                <nav class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation" id="navbar">                <div class="navbar-header">                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">                    <span class="sr-only">Toggle navigation</span>                    <img src="/themes/default/images/icons/bars.png" alt="" />                </button>            </div>            <div class="collapse navbar-collapse" id="navbar-collapse-main">                <ul class="nav navbar-nav" id="yw0"><li class="active"><a href="/site/pageiew=home">Home</a></li><li><a href="/site/login">Login</a></li></ul>            </div>            <div class="notice"></div>        </nav>        <div class="row" id="content"><br/>Welcome to <b><a href="http://www.multicraft.org">Multicraft</a></b>, the Minecraft server control panel.<br/><div class="introbar">    <a href="/site/login"><img src="/themes/default/images/icons/login_large.png" alt="" /> <span>Login</span></a><a href="http://multicraft.org/site/docs" id="yt0"><img src="/themes/default/images/icons/help_large.png" alt="" /> <span>Help</span></a><a href="/site/pageiew=about"><img src="/themes/default/images/icons/about_large.png" alt="" /> <span>About</span></a></div></div>    </div></div><script src="/themes/default/js/bootstrap.min.js"></script><script src="/js/multicraft.js"></script><script type="text/javascript">/*<![CDATA[*/jQuery(function($) {jQuery('body').on('click','#yt0',function(){if(confirm('You are leaving your control panel.\n\nYou will be forwarded to the documentation on the official Multicraft website.')) {jQuery.yii.submitForm(this,'http://multicraft.org/site/docs',{});return false;} else return false;});});/*]]>*/</script></body></html>/
30.08 05:13:35 [Server] WARN A JSONObject text must begin with '{' at 1 [character 2 line 1]
30.08 05:13:35 [Server] WARN org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
30.08 05:13:35 [Server] WARN at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
30.08 05:13:35 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:195)
30.08 05:13:35 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:319)
30.08 05:13:35 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
30.08 05:13:35 [Server] WARN at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:59)
30.08 05:13:35 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.08 05:13:35 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
30.08 05:13:35 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
30.08 05:13:35 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
30.08 05:13:35 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
30.08 05:13:35 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
30.08 05:13:35 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
30.08 05:13:35 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
30.08 05:13:35 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by Jogib** [comment]
@JayWood 
I also noticed right now, that several options are missing in the plugin.yml file?

In the Wiki i read that the follow options should be there:
lang: "en"
update_interval: 1500
url: "http://playground.dev"
key: ""

The only option i have is the "key".

When manually adding the rest and then running the "/woo check" command i get the following output:
30.08 05:37:57 [Server] WARN No data key
30.08 05:37:57 [Server] INFO No purchases available - please try again soon.

**Comment by JayWood** [comment]
Yup was gonna just ask you that, seems your config was wiped. Probably an issue with the `/woo register` command.

**Comment by JayWood** [comment]
@Jogib on the plus side, I know where I need to put another check now :smile:

**Comment by Jogib** [comment]
@JayWood 
I finally got it to work..

I had to do the following:
Add the missing options to the config.yml
Mark the product as downloadable in woocommerce (read in a previus issue that this was i requirement), though it's not stated in the wiki.

Though - "/woo check" still throws a "30.08 06:31:22 [Server] WARN No data key" in the console.

And finally one more thing.
When a purchase has been processed and the user is NOT online the follow error occurs in the console:
30.08 06:27:44 [Server] WARN null
30.08 06:27:44 [Server] WARN java.lang.NullPointerException
30.08 06:27:44 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:166)
30.08 06:27:44 [Server] WARN at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18)
30.08 06:27:44 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
30.08 06:27:44 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
30.08 06:27:44 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
30.08 06:27:44 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
30.08 06:27:44 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by JayWood** [comment]
> Though - "/woo check" still throws a "30.08 06:31:22 [Server] WARN No data key" in the console.

This is supposed to happen, it's just a debug message. I'll de-escalate it to info instead.

> When a purchase has been processed and the user is NOT online the follow error occurs in the console

Known issue, fix was in #108 PR - has yet to be merged into master. Hope to do that sometime this week. Saturday at the latest.

**Comment by JayWood** [comment]
Jogib - Just want to say thanks for taking the time to debug this issue with me, it's greatly appreciated. I can't say how many times people open tickets and never follow up.

**Comment by Jogib** [comment]
@JayWood 
Glad to hear the "no data key" isn't a bug, but just a message.

Hope i helped you out, with this JSON error :)
Will be looking forward to af new release.

**Comment by JayWood** [comment]
Closing this, any on-going issues can be followed in the above thread.
