### ISSUE TITLE
php + A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by falmon** [WooMinecraft/WooMinecraft#112]
problem with /woo check

```[04:16:34] [Server thread/WARN]: [WooMinecraft] Logging an improper server response [04:16:34] [Server thread/ERROR]: [WooMinecraft] /<!DOCTYPE html><html><head><!-- HTML meta URL redirect - generated by www.rapidtables.com --><meta http-equiv="refresh" content="0; url=http://www.twsmc.net"></head><body></body></html>/ [04:16:34] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1] [04:16:34] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1] [04:16:34] [Server thread/WARN]: at org.json.JSONTokener.syntaxError(JSONTokener.java:433) [04:16:34] [Server thread/WARN]: at org.json.JSONObject.<init>(JSONObject.java:195) [04:16:34] [Server thread/WARN]: at org.json.JSONObject.<init>(JSONObject.java:319) [04:16:34] [Server thread/WARN]: at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142) [04:16:34] [Server thread/WARN]: at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31) [04:16:34] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [04:16:34] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [04:16:34] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [04:16:34] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [04:16:34] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [04:16:34] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [04:16:34] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [04:16:34] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [04:16:34] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source) ```

config.yml:
`
lang: "en"

update_interval: 1500

url: "http://twsmc.net" # or http://www.twsmc.net = same problem

key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

debug: true`

i'm useing https://github.com/WooMinecraft/WooMinecraft/releases 18#
wordpress 4.6 - 1.0.8

**Comment by falmon** [comment]
i fixed redirect, now when i /woo check I get same error + i got all page php on console 
http://pastebin.com/YLGYggPY

**Comment by JayWood** [comment]
@falmon I can see you're using WP Super cache, have you tried disabling the cache plugin and checking? If that works, you may want to add pages with a URL parameter of `wmc_key` to the exclusion list in the caching plugin?

Also if I go to the non www version, it's redirecting me to www, so you'll want to use the url with www based on your DNS settings.

As well most of the simplest thing, make sure the plugin is activated.

**Comment by falmon** [comment]
@JayWood I Fix the problem . 
it was the mein page problem, I add /shop after www.twsmc.net in config after the its work



```
lang: "en"

update_interval: 1500

url: "http://www.twsmc.net/shop"

key: "*************************"

debug: false
```

thank you ^.^

**Comment by JayWood** [comment]
Sounds good, closing.
