### ISSUE TITLE
Doing /woo register doesn't work

### ISSUE THREAD

**Issue by TheGamerBeast13** [WooMinecraft/WooMinecraft#118]
When I do /woo register it says in chat Usage: /woo check. If am doing anything wrong please tell me as I am new to this plugin

**Comment by JayWood** [comment]
`/woo register` is no longer a command. It was creating some issues and was more problems than it was worth, you need to setup the key manually, here's quick how-to - https://github.com/WooMinecraft/WooMinecraft/wiki/Step-1:-Server-Plugin-Installation#plugin-config

**Comment by TheGamerBeast13** [comment]
where on the wordpress page am I supposed to find the key to put in the config.

**Comment by JayWood** [comment]
Think of the key like a password, only you should know it. You can create your own key and put it in both places.

For the config.yml make sure to encase the key in double quotes `"`

For the wordpress side, here ya go - https://github.com/WooMinecraft/WooMinecraft/wiki/Step-2:-Setting-up-the-wordpress-side

Basically make your own key ( how ever long/short you want ) and put it in both locations.

**Comment by TheGamerBeast13** [comment]
oh ok thanks

**Comment by spannerman79** [comment]
@JayWood perhaps changing the plugin config comments to actually state it.
Like for example change it to ;
```# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "http://playground.dev"

# This must match the WordPress key in your admin panel for WooMinecraft
# This is a key that YOU set, both needing to be identical in the admin panel
# and in this config file
# For security purposes, you MUST NOT leave this empty.
key: ""

# Set to true in order to toggle debug information
debug: false
`

**Comment by JayWood** [comment]
Issue resolved, and thanks for the PR @spannerman79
