### ISSUE TITLE
Resending order from WP control panel issue

### ISSUE THREAD

**Issue by timitimitimi** [WooMinecraft/WooMinecraft#126]
(latest version - multiserver) when you click to resend, on server, /woo check gives "all purchased processed" as if it detects it, but wont run any commands.

**Comment by JayWood** [comment]
@timitimitimi are you using the latest Java plugin version as well? I tested this and it was working with that one.

**Comment by timitimitimi** [comment]
I am, will do more testing today.

**Comment by JayWood** [comment]
@timitimitimi any updates on your tests?

**Comment by timitimitimi** [comment]
Bug is there.

**Comment by JayWood** [comment]
This should be fixed in the latest dev WP version.

**Comment by JayWood** [comment]
Closing in favor of WP-Related ticket above.
