### ISSUE TITLE
Updating WooMinecraft's Java Practices.

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#127]
Ever since I left I was able to enhance my Java skills. I have learned a lot about Java efficiency and what not. 
I am updating WooMinecraft's main branch local to follow the best practices as far as abstraction, encapsulation and what not. 

The PR should be ready today or tomorrow.

**Comment by JayWood** [comment]
@TekkitCommando thanks - remember tickets aren't a means of chat, just submit the PR we can chat there 😄
