### ISSUE TITLE
Not Processing Commands

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#130]
The following was from a private message on my profile on Spigot Forums:

Commands were received from the server:
```
[12:54:09] [Server thread/INFO]: RubenKo91 issued server command: /woo check
[12:54:11] [Server thread/INFO]: [WooMinecraft] Sending Request
[12:54:11] [Server thread/INFO]: [WooMinecraft] URL Config Field: http://127.0.0.1
[12:54:11] [Server thread/INFO]: [WooMinecraft] Headers: [Date: Mon, 16 Jan 2017 11:54:09 GMT, Server: Apache/2.4.7 (Ubuntu), X-Powered-By: PHP/5.5.9-1ubuntu4.20, Content-Length: 84, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: application/json; charset=UTF-8]
[12:54:11] [Server thread/INFO]: [WooMinecraft] HTTP Response Code: 200
[12:54:11] [Server thread/INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"RubenKo91":{"282":["pex user %s group add proefperiode"]}}}
```

Server command of `/woo check` still returned 'no purchases are available'.

From another user:

```
[03:45:46 INFO]: [WooMinecraft] Sending Request
[03:45:46 INFO]: [WooMinecraft] URL Config Field: http://shop.retardedmc.tv
[03:45:46 INFO]: [WooMinecraft] Headers: [Date: Wed, 11 Jan 2017 02:45:50 GMT, Server: Apache/2.2.22, Connection: close, Transfer-Encoding: chunked, Content-Type: application/json; charset=UTF-8]
[03:45:46 INFO]: [WooMinecraft] HTTP Response Code: 200
[03:45:46 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"TooSoMuch":{"17":["group %s Eisen"],"16":["group %s Eisen"]}}}
[03:45:56 INFO]: [WooMinecraft] Sending Request
[03:45:56 INFO]: [WooMinecraft] URL Config Field: http://shop.retardedmc.tv
[03:45:56 INFO]: [WooMinecraft] Headers: [Date: Wed, 11 Jan 2017 02:46:00 GMT, Server: Apache/2.2.22, Connection: close, Transfer-Encoding: chunked, Content-Type: application/json; charset=UTF-8]
[03:45:56 INFO]: [WooMinecraft] HTTP Response Code: 200
[03:45:56 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"TooSoMuch":{"17":["group %s Eisen"],"16":["group %s Eisen"]}}}
```

**Comment by madmaty** [comment]
Omg I am having this exact same problem. I have been trying to figure it out for hours. 

`madmaty issued server command: /woo check
[10:12:53] [Server thread/INFO]: [WooMinecraft] Sending Request
[10:12:53] [Server thread/INFO]: [WooMinecraft] URL Config Field: *******
[10:12:53] [Server thread/INFO]: [WooMinecraft] Headers: [Date: Fri, 20 Jan 2017 10:03:18 GMT, Server: Apache, X-Powered-By: PHP/5.4.45, Expires: Thu, 19 Nov 1981 08:52:00 GMT, Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0, Pragma: no-cache, Set-Cookie: PHPSESSID=bcp0onj4iu6gn5ua27nb5os3t0; path=/, Upgrade: h2, Connection: Upgrade, Keep-Alive, Keep-Alive: timeout=3, max=20, Transfer-Encoding: chunked, Content-Type: application/json; charset=UTF-8]
[10:12:53] [Server thread/INFO]: [WooMinecraft] HTTP Response Code: 200
[10:12:53] [Server thread/INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"madmaty":{"1657":["givecar %s BLACK","givecar %s BLACK"],"1656":["say test item bought"],"1655":["say %`

**Comment by madmaty** [comment]
This recently started about maybe 2 hours ago, I have not changed anything on the server. maybe its related to the other problem...

> WARN [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1] 
21.01 13:02:24 [Server] WARN org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1] 
21.01 13:02:24 [Server] WARN at org.json.JSONTokener.syntaxError(JSONTokener.java:433) 
21.01 13:02:24 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:195) 
21.01 13:02:24 [Server] WARN at org.json.JSONObject.<init>(JSONObject.java:319) 
21.01 13:02:24 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:135) 21.01 13:02:24 [Server] WARN at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18) 21.01 13:02:24 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) 
21.01 13:02:24 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
21.01 13:02:24 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
21.01 13:02:24 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 21.01 13:02:24 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by nxfifteen** [comment]
@JayWood I had the same problem with my setup. I fixed it by putting my world name in the config file as a white-listed world.

Not sure if this helps you but thought I'd mention it

**Comment by madmaty** [comment]
@nxfifteen   that worked to get the items flowing but its now throwing new errors before it gives the items


```
Sending Request 
23.01 15:56:19 [Server] INFO [WooMinecraft] URL Config Field: XXXXXXXXXXX
23.01 15:56:19 [Server] INFO [WooMinecraft] Headers: [Date: Mon, 23 Jan 2017 
12:46:43 GMT, Content-Type: application/json; charset=UTF-8, Transfer-Encoding: chunked, Connection: keep-alive, X-Powered-By: PHP/5.4.45, Expires: Thu, 19 Nov 1981 
08:52:00 GMT, Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0, Pragma: no-cache, Vary: Accept-Encoding,Cookie, Set-Cookie: PHPSESSID=XXXXXXXXXXX; path=/, Server: cloudflare-nginx, CF-RAY: 325b5983adad3d4f-CPH] 23.01 
15:56:19 [Server] INFO [WooMinecraft] HTTP Response Code: 200 23.01 
15:56:19 [Server] INFO [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"madmaty":{"1734":["givecar %s BLACK"],"1657":["givecar %s BLACK","givecar %s BLACK"],"1656":["say test 
23.01 15:56:20 [Server] WARN [WooMinecraft] Status code is not 200 got: 301 23.01 
15:56:20 [Server] WARN java.lang.Exception: Status code is not 200 got: 301 23.01 
15:56:20 [Server] WARN at com.plugish.woominecraft.Util.RcHttp.send(RcHttp.java:106) 
23.01 15:56:20 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:204) 
23.01 15:56:20 [Server] WARN at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31) 
23.01 15:56:20 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
23.01 15:56:20 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
23.01 15:56:20 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) 
23.01 15:56:20 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
23.01 15:56:20 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) 
23.01 15:56:20 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) 
23.01 15:56:20 [Server] WARN at java.lang.Thread.run(Thread.java:745) 23.01 
15:56:20 [Server] INFO Car given to madmaty 23.01 15:56:20 [Server] INFO Car given to madmaty
```

**Comment by JayWood** [comment]
@nxfifteen @madmaty what was your config for the world white-listing, was it just empty, key not set? Trying to determine how to handle that issue on the Java side.

**Comment by nxfifteen** [comment]
@JayWood my config file was as per the default

`# Allowed words the player need to be on to run the commands.
# Disabled by default!
# whitelist-worlds:
#  - world`

I think I'd miss read the comments and assumed "Disabled by default" meant all worlds were white listed by default - which I know makes it a user error

**Comment by madmaty** [comment]
Previous config

`# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 60

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "https://geekscraft.ca"

# This must match the WordPress key in your admin panel for WooMinecraft
# This is a key that YOU set, both needing to be identical in the admin panel
# and in this config file
# For security purposes, you MUST NOT leave this empty.
key: "HIDDEN"

# Allowed words the player need to be on to run the commands.
# Disabled by default!
# whitelist-worlds:
#  - home

# Set to true in order to toggle debug information
debug: true
`


new config

`# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 60

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "https://geekscraft.ca"

# This must match the WordPress key in your admin panel for WooMinecraft
# This is a key that YOU set, both needing to be identical in the admin panel
# and in this config file
# For security purposes, you MUST NOT leave this empty.
key: "HIDDEN"

# Allowed words the player need to be on to run the commands.
# Disabled by default!
whitelist-worlds:
 - home

# Set to true in order to toggle debug information
debug: true
`

I would bet if you just add a default so it pulls a world name set in server config this would go away

**Comment by JayWood** [comment]
@madmaty weird, when I tested this originally I simply didn't have the whitelist-worlds key at all, so I had assumed by adding it and commenting it out, it would be the same thing.

Either way, I'll do more testing here to verify, and it sounds like I need a more logical check here: https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L167

**Comment by madmaty** [comment]
If you just have it auto whitelist the value form line 31 of server.properties   (level-name=value)  then reword the default config details to say  something like   add additional worlds list them here    prob could be all done with this error :)
