### ISSUE TITLE
Unsupported major.minor version

### ISSUE THREAD

**Issue by thebarbaricbuffalo** [WooMinecraft/WooMinecraft#131]
Log Link: http://pastebin.com/C60uHv7v

### Server Information:
Host: Kimsufi /Private Host
URL:Buffaloservers.us
WordPress URL:Buffaloservers.us

### Config.yml
url: Config not generated

So i tryed loading it it as a plugin and it didnt work. Spigiot sees it on version 1.10.2 but it says 

at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: java.lang.UnsupportedClassVersionError: com/plugish/woominecraft/WooMinecraft : Unsupported major.minor version 52.0

I've tried using different MC versions and different Woo MC versions. No luck.

Cheers

**Comment by JayWood** [comment]
@thebarbaricbuffalo Your log has no mentions of this error? Wrong log maybe?

**Comment by spannerman79** [comment]
> Unsupported major.minor version 52.0

http://lmgtfy.com/?q=Unsupported+major.minor+version+52.0

**Comment by TekkitCommando** [comment]
If you're asking how to fix unsupported Major minor version then you need to update your servers host machine to Java 8.

**Comment by JayWood** [comment]
Closing - unrelated to the plugin.
