### ISSUE TITLE
"No purchases available" (Bug)

### ISSUE THREAD

**Issue by dordsor21** [WooMinecraft/WooMinecraft#136]
https://hastebin.com/ipuqexuget.md

### Server Information:
Host: ..OVH.? 
http://www.athion.net
http://www.athion.net

### Config.yml
https://hastebin.com/mekuxaquqo.bash
key is hidden cos security shizzles

**Comment by JayWood** [comment]
See #130 

Also, set `debug: true` in your config.

**Comment by JayWood** [comment]
`[00:58:46 INFO]: [WooMinecraft] Data check was not an instance of JSONObject, so bailing.`

This tells me that the data it received from the server was empty. Which means on the WordPress side of things you either have A.) no orders completed, or B. ) no orders at all with commands saved.

**Comment by dordsor21** [comment]
There were (and still are) three orders, each with commands waiting on the WP site

**Comment by JayWood** [comment]
This tells me otherwise - `{"success":true,"data":[]}` Data array is empty in your log. If you're using the pre-release that may be why.

**Comment by dordsor21** [comment]
This is the bug I suppose^ I'll look to see if there might be something blocking it in wp

**Comment by dordsor21** [comment]
should be made more obvious the product needs to be set as complete

**Comment by JayWood** [comment]
Consider the wiki - https://github.com/WooMinecraft/WooMinecraft/wiki/Step-3:-Creating-A-Package
