### ISSUE TITLE
Expired Commands

### ISSUE THREAD

**Issue by Arctomium** [WooMinecraft/WooMinecraft#140]
Hey I'm wondering if you can add or if it's already been added the ability to run a command when the purchase expires like Buycraft does. This is a really important feature for Premium ranks and also do you have the feature of automatic billing?

**Comment by spannerman79** [comment]
Dupe #100

**Comment by JayWood** [comment]
@Arctomium Automatic billing is untested at this time, but you would need something like WooCommerce Subscriptions, even then I'm not sure the commands would refresh, etc..

Expiration is a planned feature, but again, may tie into a subscription plugin, and rather or not I create my own has been undetermined at this point given there are free subscription plugins out there.

**Comment by Arctomium** [comment]
Yes but how would I make a subscription plugin to run commands when the subscription expires? Without that core feature using WooMinecraft is essentially pointless.

**Comment by ethernity4ever** [comment]
use your permission plugin and give him perms for a limited time period

**Comment by spannerman79** [comment]
> free subscription plugins out there

@JayWood which one/s would you recommend trying/testing?  I know this is a closed and old-ish issue but something in black and white would be "nice"

As the only alternative is WooSubs ( https://github.com/WooMinecraft/WooMinecraft/issues/100#issuecomment-244030608 )

**Comment by JayWood** [comment]
@spannerman79 The one thing around subscription plugins is that there's no way to run a command when subscription is done out of the box.

But, if you're feeling adventurous you may want to give this one a try ( without the $200 price tag ) - https://wordpress.org/plugins/yith-woocommerce-subscription/

Once I figure out what the hell is going on with the Jersey client I'm working on, this is next on my list.

**Comment by esmith715** [comment]
You could always see if there is an API for a subscription plugin you could always code in the extra feature of commands being sent at expiration. PHP and WordPress is pretty simple to work with it.

**Comment by Arctomium** [comment]
Just using Pex timed ranks now.
