### ISSUE TITLE
My server is crashing when /woo check is used 

### ISSUE THREAD

**Issue by Harryols** [WooMinecraft/WooMinecraft#141]
My server is crashing when /woo check is used.
I get this log:

**Log Link: http://pastebin.com/p1x68fMG ** 

### Server Information:
* **Host: harryo.dk **
* **URL: [http://harryo.dk/](http://harryo.dk/) **
* **WordPress URL: [http://harryo.dk/](http://harryo.dk/) **

**Comment by JayWood** [comment]
@Harryols I have a sneaky suspicion that it's to do with the `.dk` TLD extension. I'll do some research and see.

**Comment by Harryols** [comment]
Thanks :D

**Comment by JayWood** [comment]
@Harryols the `.dk` extension is there, the stack trace seems related specifically to HTTP utilities ( a 3rd party library ).

What version of java are you using?

**Comment by JayWood** [comment]
No response in over a month, closing.
