### ISSUE TITLE
[Future-Request] Requirement of a product

### ISSUE THREAD

**Issue by BirkhoffLee** [WooMinecraft/WooMinecraft#144]
For example, I'm having a rank shop, let's say I have rank "Kid", "Adult".

If someone bought "Kid" and he wants to buy "Adult", we should give him an upgrading price, which is lower then the regular price.

Thus, we will need the requirement feature which can detect that if people have reached the requirement of the product.

My suggestion is to use PlaceholderAPI to implement this. Server owners are gonna create JavaScript placeholders which can handle the if/else statements or something like that, the WooMinecraft plugin just need to make sure that the certain placeholer returns true.

**Comment by JayWood** [comment]
I'm not entirely sure how to implement this, and the details seem to sway between both a WordPress and Java implementation.

At this time, I'm not looking to add any more complexity to the project. I do, however agree that this would be beneficial. For now I'll tag it as help-wanted and see if anyone wants to open a PR.

**Comment by xOrlxndo** [comment]
I'd be willing to help with this :)

**Comment by JayWood** [comment]
It's been awhile, but found a work around - https://wordpress.org/plugins/woocommerce-product-dependencies/

Closing.
