### ISSUE TITLE
[Improvement] Validate config at startup instead of checks

### ISSUE THREAD

**Issue by BirkhoffLee** [WooMinecraft/WooMinecraft#145]
I found that WooMinecraft validates the configuration file every time it checks orders. Why would you do that? That would waste performance. You should validate it at startup, if it doesn't meet the requirements, the plugin should be disabled.

**Comment by JayWood** [comment]
Good point! This should be moved - https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L118
