### ISSUE TITLE
Move to REST client

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#147]
Will be moving to a more RESTful client in the future.

**Comment by JayWood** [comment]
After a TON of research into POJOs today, I've decided to change the JSON output by the commands. This puts more work on the java side of things, instead of 'keying' orders by player, we'll now have to iterate over them and build an internal reference list.

Not a huge deal, but this affords me the ability to use the Jersey library for JSON calls.

```
{
    "server_key": "amazingserverkey",
    "order_data": [
        {
            "player": "Phyrax",
            "orderID": 163,
            "commands": [
                "Just one variation",
                "Yet Another Command"
            ]
        }
    ]
}
```

**Comment by JayWood** [comment]
Running into a wall here. Would love some input from anyone on the interwebs somewhere.

See this thread for details: https://www.spigotmc.org/threads/messagebodyreader-not-found-for-media-type-application-json.267279/

**Comment by ThisIzEthan** [comment]
@JayWood It seems this is a common error and most people simply switched libraries, the common switch was to jenson or jackson but gson is also an option. I don't know a solution for your current library choice.

**Comment by JayWood** [comment]
I know I'm MONTHS late here LOL - but Gson is a viable option, for which I may make the move soon.

**Comment by ethsmith** [comment]
@JayWood Was the new updates you added, this new rest implementation you were wanting to do? I ask because if we are at a point where I can expect the REST code to not change drastically, I can come back for a bit and work on signs and what not. 

P.S. This is TekkitCommando

**Comment by JayWood** [comment]
I basically am not using the old branch and code provided above, it's on a new branch `release/1.2.0` and I started from scratch straight from master.

**Comment by JayWood** [comment]
For those following along, the endpoint is coming along nicely:

New endpoint URL format
`/wp-json/wmc/v1/server/$wmc_key$`
> note if you're using your site's `/shop` in the config, this will no longer be necessary and will break

New format ( valid json )
```{
  "code": "invalid_key",
  "message": "Key provided in request is invalid.",
  "data": {
    "status": 200
  },
  "orders": [
    {
      "player": "Phyrax",
      "order_id": 23,
      "commands": [
        "give Phyrax apple 1"
      ]
    }
  ]
}```

Successful order pull
![](https://i.gyazo.com/7f30682884b6dfb0b04f9993e958cbd1.png)

Successful error message.
![](https://i.gyazo.com/7533f3088401391d4b54d2881642ab97.png)
