### ISSUE TITLE
301 ERROR 

### ISSUE THREAD

**Issue by izakhearn** [WooMinecraft/WooMinecraft#150]
We receive  a 301 error each time no matter what we change any idea to what it could be 
Console output: 
> https://hastebin.com/oxewiqoguv.sm

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/wiki#orgjsonjsonexception-a-jsonobject-text-must-begin-with--at-1-character-2-line-1

> Make sure the URL you're using has zero redirects, ie from a non www domain like http://example.com to a www.example.com domain.

https://en.wikipedia.org/wiki/HTTP_301

**Comment by izakhearn** [comment]
Yeah we checked we redirect http to https but as you can see we send it directly to the https part and also upon the command being executed that is the about the 10th time it repeats from one purchase
Here is my config 

```
# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "https://nethercentral.tk/store"

# This must match the WordPress key in your admin panel for WooMinecraft
# This is a key that YOU set, both needing to be identical in the admin panel
# and in this config file
# For security purposes, you MUST NOT leave this empty.
key: "REMOVED FOR SECURITY"

# Allowed words the player need to be on to run the commands.
# Disabled by default!
whitelist-worlds:

# Set to true in order to toggle debug information
debug: true 
```

**Comment by spannerman79** [comment]
> Yeah we checked we redirect http to https

Exactly, which throws a 301 - which you cannot do.

**Comment by izakhearn** [comment]
But we are pointing the plugin straight to https so there are no redirect between them

**Comment by spannerman79** [comment]
`[Sat, 22. Apr 2017 08:11:01 WARN] java.lang.Exception: Status code is not 200 got: 301` clearly your not.

>The HTTP response status code 301 Moved Permanently is used for **permanent URL redirection**

**Comment by izakhearn** [comment]
Okay well the i dont know what to do because we want to force https on the store for security purposes 
and in my config i even made sure it poinst to https 
```
# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "https://nethercentral.tk/store" 
```

**Comment by spannerman79** [comment]
https://tools.ietf.org/html/rfc6797

non plugin issue

**Comment by izakhearn** [comment]
Okay will see what we can do about the HTTPS problem

**Comment by JayWood** [comment]
HTTPS is not the problem. Your website uses application-based bot authentication which is causing the redirect. If I go to the URL in your config as a fresh user, I'm given this URL instead https://nethercentral.tk/store/?v=edb5dc74af1c

That is your redirect. This plugin does not support redirects like that. For obvious reason I also checked to see if your install supported the wp-json/ endpoint, which would resolve this in an upcoming update. However it doesn't either.

The problem here is your host, your server is causing the redirect, and therefore I cannot fix that nor provide a workaround to application-based bot verifications at this time.

**Comment by izakhearn** [comment]
Thanks for clearing that up i have contacted my web host and hopefully they
can provide a fix

**Comment by JayWood** [comment]
No problem @izakhearn you're not the first to have that issue, especially with `.tk` top-level domains.

**Comment by izakhearn** [comment]
We fixed it by pointing it to https://nethercentral.tk/store/shop/ and disabling a setting in woocommence for region or something like that

**Comment by JayWood** [comment]
Ahh, so store is your wordpress install, not the root site. That explains why I could not access the JSON feed. Glad to hear it's fixed!
