### ISSUE TITLE
[MAJOR] commands are being executed MULTIPLE times!

### ISSUE THREAD

**Issue by BirkhoffLee** [WooMinecraft/WooMinecraft#152]
**Log Link:** https://pastebin.com/CNM6bndg

### Server Information:
* **Host:** minemystery.net
* **URL:** https://minemystery.net
* **WordPress URL:** https://store.minemystery.net

### Config.yml
* **url:** https://pastebin.com/cT4PTnww

**Comment by BirkhoffLee** [comment]
I created a test product intended for testing this, and the commands are just repeatedly executing. I can't really provide any more proof expect screenshots but I've said the results clearly in words so I think it's no need to take one.

**Comment by JayWood** [comment]
See #122

**Comment by BirkhoffLee** [comment]
Changing the url to `http://site_base_dir/index.php/shop/` does not do the work. I'm using official Wordpress Docker image running behind an nginx reverse proxy.

**Comment by JayWood** [comment]
I've been working to update the code to use the WP Rest API here: WooMinecraft/woominecraft-wp#37

I also have been working on integrating the Java Jersey client in the MineCraft plugin. Once all is said and done, I'm sure we won't have anymore issues.

**Comment by BirkhoffLee** [comment]
That's awesome. I look forward to see your work soon.

**Comment by JayWood** [comment]
Found a second instance of this again today. The issue was a redirect was occurring during the `POST` proceedure. Unfortunately without server level access, I cannot debug further.

Will be working to hopefully beef up debugging surrounding this issue.

**Comment by JayWood** [comment]
Bare minimum goal here:
- [ ] do NOT give items out until commands are sent to the server
- [ ] Add debugging information to the [RcHttp::send()](https://github.com/WooMinecraft/WooMinecraft/blob/320e6c1a49dca55cd371e41fb5002f105be8505c/src/main/java/com/plugish/woominecraft/Util/RcHttp.java#L89) method.

**Comment by JayWood** [comment]
@BirkhoffLee this seems to be fixed with this version https://github.com/WooMinecraft/woominecraft-wp/tree/feature/dockerize/src

**Comment by JayWood** [comment]
Marking as fixed, see WooMinecraft/woominecraft-wp#47 for further info.
