### ISSUE TITLE
Performing commands over certain users.

### ISSUE THREAD

**Issue by WyRe** [WooMinecraft/WooMinecraft#153]
I cannot get that page in my Wordpress dashboard:

https://camo.githubusercontent.com/9a9fdbe874e85eabbd3714afe367dd570b5bb335/687474703a2f2f692e696d6775722e636f6d2f797446717a6b6a2e706e67

also how can be performed commands over the user? I mean, when a user purchase the product, I would need to perform the command over him to promote (in case of my product would be a rank in permissions, for instance)

**Comment by WyRe** [comment]
Oh, to the first one, I've already found where is really, in the WooCommerce settings page:
![captura de pantalla de 2017-05-09 21-14-27](https://cloud.githubusercontent.com/assets/4059108/25868338/a0a07f48-34fc-11e7-8969-094e77849768.png)
You should modify your wiki.

But to the second one I've the question :)

**Comment by JayWood** [comment]
Commands should include `%s` in the command, it will be replaced with the user's name.

For instance: `give %s apple 1`
Is actually `give phyrax apple 1`

**Comment by WyRe** [comment]
Thank you so much. :)

**Comment by TekkitCommando** [comment]
@WyRe It will replace the %s with the MC username of the player, not Wordpress name.

**Comment by WyRe** [comment]
@TekkitCommando then? How the plugins will relate the wordpress user who buy the product with the MC player who must receive the product? If they have not the same nick...

**Comment by TekkitCommando** [comment]
@WyRe the players puts in his MC name when buying a product.
