### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by 1visible** [WooMinecraft/WooMinecraft#154]
**Log Link:** https://hastebin.com/egasecocoq.md

### Server Information:
* **Host:** mc4.boxtoplay.com:26888
* **Version:** Spigot 1.11.2
* **Plugin:** Latest version
* **WordPress URL:** hunting.890m.com (Wordpress latest version)

### Problems:

I recently installed WooMinecraft plugin on my server in 1.11.2 and I noticed some problems. I checked in and my first problem (the error log is in the hastebin file) might be due to the website link given in the config file. So I tested several links: the website link, another and one that leads directly to the store. So the problem has been solved (I guess, I don't see any errors for the moment). However a problem persists: during a purchase the players receive their items, but by doing "/woo check" they can still have it and it goes on, we can do as much "/woo check" as we want to have the same item. No error in the console, and nothing abnormal in the configuration of the product on Wordpress. I don't know if it's a bug or if I made a mistake, so I hope the problem will be solved. Thanks in advance and sorry for my bad english.
Cordially,
1visible

**Comment by spannerman79** [comment]
Config issue (your end)

https://httpstatuses.com/508

Non-plugin issue
