### ISSUE TITLE
Bungeecord Support

### ISSUE THREAD

**Issue by ArctoranDev** [WooMinecraft/WooMinecraft#155]
Hi, I was wondering if this plugin has the ability to run commands across multiple servers or if there a Bungee plugin that I could put on my Bungeecord server and from there run specific commands so Bungeecord handles running commands to multiple servers?

**Comment by spannerman79** [comment]
Need to give an actual example of what you are trying to do.

There are many ways to communicate across a bungee network - all depends on what you are trying to achieve.

**Comment by TekkitCommando** [comment]
He did, he said he wanted the commands sent to all the servers. @Arctomium not at this moment I think, but in the future we hope.

**Comment by spannerman79** [comment]
> Hi, I was wondering if this plugin has the ability to run commands across **multiple** servers

Multiple != all

**Comment by TekkitCommando** [comment]
If there was support for sending to all servers then there would be support for specifying specific servers. Wouldn't be too different.

**Comment by JayWood** [comment]
There is no Bungee cord support currently.

Feel free to submit a PR if you have the Java/PHP skillset though, I'm always open to that 😄

**Comment by Arctomium** [comment]
Would it work to use Pex with MySQL? But just have the users stored in MySQL and have all the network ranks setup with the different permissions and groups on each server?

**Comment by spannerman79** [comment]
Use SexyPex for that.  Or you could use Luckperms instead

**Comment by JayWood** [comment]
In simple terms, this plugin is designed to just run commands as a console user. So in short, if a console user could run the pex commands, then yes.

That said, if there are special characters in the commands, it may have problems, but I identify those as I see them, if/when I see them.

**Comment by Arctomium** [comment]
Well I tried SexyPEX, paid a stupid amount for it only to have it give me errors and somehow completely remove all the Pex commands.

**Comment by Arctomium** [comment]
Sorry accidentally hit close and comment instead of comment.

**Comment by TekkitCommando** [comment]
Might PM the dev.

**Comment by Drison64** [comment]
If you want to do this, you need MySQL, Some server connected to BungeeCord with WooMinecraft and PermissionsEX, and servers connected to Bungeecord all with PermissionsEX

Just simply Connect PermissionsEX to the MySQL (With backend) (You need to connect it at all servers, not for BungeeCord) If you need help, search on Youtube `PermissionsEX backend` or something like that.

**Comment by JayWood** [comment]
Multi-server support is currently implemented. However, 'one-command-for-all-servers' is not, you would need to create commands for ALL servers, for EACH product.

This is not on my roadmap but will tag as help-wanted should anyone want to dive in.

**Comment by Peda1996** [comment]
I have updated the plugin, therefore also bungee is also supported
https://github.com/WooMinecraft/WooMinecraft/pull/206

(command is now /bwoo for checking for new purchases)
