### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by jhonwds** [WooMinecraft/WooMinecraft#157]
Any chance we are having 1.12 support soon? Thank you :)

**Comment by JayWood** [comment]
@jhonwds Once the REST API implementation is complete, I plan to start building the latest versions again.

**Comment by JayWood** [comment]
@jhonwds looking at #160 this looks to be working on 1.12 though I've not tried myself.

**Comment by Elxafil** [comment]
Was there any news on this @JayWood?

**Comment by JayWood** [comment]
Not as of yet @Elxafil - my work has over loaded me for now - I should be able to get back into the groove of things soon.

**Comment by JayWood** [comment]
Going to try and get a build setup for 1.12 today, my computer was recently wiped, so I have to reinstall everything.
