### ISSUE TITLE
No purchases available

### ISSUE THREAD

**Issue by Drison64** [WooMinecraft/WooMinecraft#158]
Log Link: Sorry, i can't get log from it...

Server Information:
Host: 89.203.250.162 (If you want IP of server)
URL: http://dustcraft.eu
WordPress URL: http://dustcraft.eu

Config.yml
url: http://dustcraft.eu

When i type `/woo check`, it will type me `No purchases available - please try again soon.`, but i have a purchase on Wordpress. Can you please help me?

**Comment by spannerman79** [comment]
```
curl -Is http://dustcraft.eu/                                                                       
HTTP/1.1 404 Not Found
Date: Thu, 22 Jun 2017 20:40:39 GMT
Server: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.24
X-Powered-By: PHP/5.6.24
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Link: <http://dustcraft.eu/wp-json/>; rel="https://api.w.org/"
Content-Type: text/html; charset=UTF-8
```

Non plugin issue.  Sort out your website first

**Comment by Drison64** [comment]
How do you think `Sort out your website first`? Can you please help me with it?

**Comment by Drison64** [comment]
Oh, i think that, minecraft server side is OK, but Wordpress not, if i go to `http://dustcraft.eu/?woo_minecraft=check&key=HIDDEN` it will show me this: `{"success":true,"data":{"Drison64":{"243":["say Drisone funguje to!"],"242":["say Drisone funguje to!"],"241":["say Drisone funguje to!"],"239":["say Drisone funguje to!"]},"Drison64":{"240":["say Drisone funguje to!"]}}}`, and i think this is OK too, but when i type `/woo check` it will say this in console: `[WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]`. What am i doing wrong?

**Comment by Drison64** [comment]
Anyone please? I need it until 30.6.2017.

**Comment by JayWood** [comment]
@Drison64 try setting your URL config to the shop page, typically at `/shop` - in  your case, this URL: `http://dustcraft.eu/shop/`

The problem is your WordPress install is not setup correctly. When going to a WordPress site, you shouldn't get a 404.

**Comment by Drison64** [comment]
That code `404` is from, that main page of Wordpress page is private now.

**Comment by Drison64** [comment]
@JayWood Ok, i fixed it, but another problem is here... Do players need to be online for command be processed?

**Comment by JayWood** [comment]
Currently there is no offline command support. It will be in the next release, which is TBD

**Comment by Drison64** [comment]
Ok, closing this issue. Thanks!
