### ISSUE TITLE
Re-build WordPress Plugin

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#16]
The WordPress plugin REALLY needs some work.  A lot of checks need to be put in place to validate data, request parameters, and a more linear JSON approach needs to be taken.

Just adding this as a note, you'll see a PR soon!

**Comment by TekkitCommando** [comment]
Sweet! :D :+1:

**Comment by JayWood** [comment]
Closing this, as of WooMinecraft/woominecraft-wp@2c4a032c3b1c7202110a58443713bf3f0838b20b WordPress plugin is stable.
