### ISSUE TITLE
Data check was not an instance of JSONObject

### ISSUE THREAD

**Issue by Stevenvdv** [WooMinecraft/WooMinecraft#161]
Hello,

Everytime wooMinecraft tries to connect to the website, this happens.

16:26:56 WooMinecraft: Sending Request
16:26:56 WooMinecraft: URL Config Field: http://playcreadome.net
16:26:56 WooMinecraft: Headers: [Date: Fri, 07 Jul 2017 14:26:56 GMT, Server: Apache/2.4.18 (Ubuntu), Content-Length: 26, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: application/json; charset=UTF-8]
16:26:56 WooMinecraft: HTTP Response Code: 200
16:26:56 WooMinecraft: Content Body Snippet (128 chars): {"success":true,"data":[]}
16:26:56 WooMinecraft: Data check was not an instance of JSONObject, so bailing.

any ideas?

**Comment by JayWood** [comment]
`{"success":true,"data":[]}` - data is empty, which means no sales have been completed ( possibly ). Review your sales, make sure all are marked as completed, re-run.

**Comment by Stevenvdv** [comment]
solved it, my fault, thanks
