### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by SkyCityCZ** [WooMinecraft/WooMinecraft#163]
How to get the key in step 1 for the plugin

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/resources/config.yml#L15..L18

**Comment by SkyCityCZ** [comment]
Can I get a tutorial, please? I don't know how to get the key....

**Comment by spannerman79** [comment]
`This is a key that YOU set, both needing to be identical in the admin panel and in this config file`
https://www.random.org/strings/?num=15&len=20&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new

**Comment by SkyCityCZ** [comment]
ok now work but if i do woo check it says no purchases available please try again later.... any help?

**Comment by SkyCityCZ** [comment]
i fixed the first issue by giving same (generated) key to here and to config  [https://preview.ibb.co/fxgth5/V_st_i.png](url)

**Comment by SkyCityCZ** [comment]
but as i said about the woocheck... i tried create test broduct with say helllo command i bought it but nothing happened

**Comment by SkyCityCZ** [comment]
and if i add commands how can i add like minecraft username of the user who bought it? like broadcast {name} hi   ??
