### ISSUE TITLE
How get key?

### ISSUE THREAD

**Issue by Marsietis** [WooMinecraft/WooMinecraft#166]
How get a key?

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/resources/config.yml#L16..L17

**Comment by Marsietis** [comment]
And other question, you must have legal account?

**Comment by Marsietis** [comment]
adn how fix 
support  [WooMinecraft] Status code is not 200 got: 301
[12:10:39] [Server thread/WARN]: java.lang.Exception: Status code is not 200 got: 301

**Comment by spannerman79** [comment]
>you must have legal account

https://help.mojang.com/customer/en/portal/articles/325947-where-can-i-buy-minecraft-

> Status code is not 200 got: 301

https://en.wikipedia.org/wiki/HTTP_301

Read https://github.com/WooMinecraft/WooMinecraft/wiki#orgjsonjsonexception-a-jsonobject-text-must-begin-with--at-1-character-2-line-1

> Make sure the URL you're using has zero redirects, ie from a non www domain like http://example.com to a www.example.com domain.

**Comment by Marsietis** [comment]
Its any ways to do it without legal?

**Comment by spannerman79** [comment]
Cracked clients never will be supported @Marsietis 

@JayWood has stated so in *several* issues. Do not ask. https://github.com/WooMinecraft/WooMinecraft/issues/113#issue-176048209
