### ISSUE TITLE
No settings

### ISSUE THREAD

**Issue by Willmaster04** [WooMinecraft/WooMinecraft#167]
Your wordpress plugin doesn't even give me any settings. I downloaded the wordpress plugin straight off github then uploaded it but there is no setting for making a key so I cannot sync it to minecraft.

**Comment by spannerman79** [comment]
Did you read the config file once you ran the plugin on your minecraft server?

I think https://github.com/WooMinecraft/WooMinecraft/blob/master/src/main/resources/config.yml#L16..L17 is pretty clear

**Comment by Willmaster04** [comment]
No - Im talking in the wordpress side there is no woominecraft settings for me

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/wiki/Step-2:-Setting-up-the-wordpress-side

**Comment by JayWood** [comment]
From the above linked page - 
>>> This page will be out of date given the 1.1 release coming soon. The settings page will be located under WooCommerce > Settings at the bottom of the page.

So like you said, `gg` - please read the full docs before opening a ticket. Settings are there.

**Comment by Willmaster04** [comment]
Thhanks so sorry this helped so much

**Comment by Willmaster04** [comment]
Thanks so sorry this helped so much
