### ISSUE TITLE
1.12 Issue

### ISSUE THREAD

**Issue by JobWieKentHemNiet** [WooMinecraft/WooMinecraft#169]
Hi,
I have run WooMinecraft on version 1.12. Everything looks good. No mistakes in the console. But now I had a quick test by buying a product and now I notice that the commands are not being executed on my server. I think this is a bug. Can it be solved? I also have an idea for a new update. A reaction like the wordpress plugin and the minecraft plugin can connect with each other so that you are sure that it is all right😅.

thanks in advance
Greetings Job.

**Comment by JobWieKentHemNiet** [comment]
**Host: hostingnet.nl
**URL: topinetwork.nl
**WordPress URL: topinetwork.nl

**Comment by spannerman79** [comment]
Read the FAQ https://github.com/WooMinecraft/WooMinecraft/wiki#faqs
Include the debug logs

**Comment by JobWieKentHemNiet** [comment]
I will be look tomorrow!😉

**Comment by LeftUse** [comment]
@JobWieKentHemNiet hey bud. 
how'd u set the ssl from cloudflare for ur website? 
can u teach me?

**Comment by spannerman79** [comment]
@LeftUse not valid or related to this issue tracker.  Contact Cloudflare directly yourself or read through their docs/FAQ.

**Comment by LeftUse** [comment]
@spannerman79 im just asking for help to him not you.
i know,. sorry.
im just really need help

**Comment by spannerman79** [comment]
@LeftUse This is an issue tracker for WooMinecraft  **ONLY**

**NOT** for Cloudflare support
**NOT** for Unrelated Tech support that is outside the scope of this issue tracker.

**Comment by JobWieKentHemNiet** [comment]
It is working now. It was the whitelist in the config😅

**Comment by JayWood** [comment]
Closing
