### ISSUE TITLE
Command cant be sent.

### ISSUE THREAD

**Issue by jasonc123456** [WooMinecraft/WooMinecraft#178]
[03:57:10 INFO]: [WooMinecraft] HTTP Response Code: 200
[03:57:10 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":tru
e,"data":[]}
[03:57:10 INFO]: [WooMinecraft] No data to process, or data is invalid.
[03:57:46 INFO]: [MysqlEcoBridge] Saving online players data...
[03:57:46 INFO]: [MysqlEcoBridge] Data save complete for 1 players.
[03:58:12 INFO]: [WooMinecraft] Sending Request
[03:58:12 INFO]: [WooMinecraft] URL Config Field: http://store.corecrafted.net
[03:58:12 INFO]: [WooMinecraft] Headers: [Server: openresty, Date: Sun, 22 Apr 2
018 19:58:18 GMT, Content-Type: application/json; charset=UTF-8, Transfer-Encodi
ng: chunked, Connection: keep-alive, X-Powered-By: PHP/7.0.28, X-Pingback: http:
//store.corecrafted.net/xmlrpc.php]
[03:58:12 INFO]: [WooMinecraft] HTTP Response Code: 200
[03:58:12 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":tru
e,"data":[]}
[03:58:12 INFO]: [WooMinecraft] No data to process, or data is invalid.
![image](https://user-images.githubusercontent.com/30266160/39099285-d09328de-46aa-11e8-8a83-19e2ec588f87.png)

![image](https://user-images.githubusercontent.com/30266160/39099290-ece92f06-46aa-11e8-834a-0fe40bf5dd06.png)

**Comment by spannerman79** [comment]
nslookup
```
nslookup store.corecrafted.net
Server:     google-public-dns-a.google.com
Address:    8.8.8.8

Name:       store.corecrafted.net
Address:    31.220.110.116
```
ipwhois

```
Source: whois.ripe.netIP Address: 31.220.110.116
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '31.220.110.0 - 31.220.110.255'

% Abuse contact for '31.220.110.0 - 31.220.110.255' is 'abuse@hostinger.com'

inetnum:        31.220.110.0 - 31.220.110.255
netname:        HOSTINGER-SHARED-HOSTING
descr:          Shared Hosting Servers
country:        SG
admin-c:        HN1858-RIPE
tech-c:         HN1858-RIPE
status:         ASSIGNED PA
mnt-by:         MNT-HOSTINGER
created:        2015-12-10T10:38:45Z
last-modified:  2015-12-10T10:38:45Z
source:         RIPE
```

Take note of netname:        HOSTINGER-**SHARED-HOSTING**

99% of the time shared hosting have a firewall filter/block of some kind that prevents WooMinecraft from operating.  This is something that WooMinecraft cannot work around - this i know from personal experience.

Grab a VPS, hell even a droplet from Digital Ocean ( ~10USD/month 2GB RAM ) would be able to easily handle apache with nginx as the reverse proxy + mysql etc.

**Comment by jasonc123456** [comment]
Thanks for your reply but do you know more about the problem like what is blocking it?

**Comment by jasonc123456** [comment]
From hostinger customer support

Hey, based on the issue, it seems that this plugin does not work on shared hosting servers, as it most likely requires root access. You should be able to use it on a VPS though :)

**Comment by ThisIzEthan** [comment]
@jasonc123456 Yes, get a VPS or Droplet like @spannerman79 said.

**Comment by jasonc123456** [comment]
Thanks for your support actually we do have our own servers which we can host on, cause the web host we r paying on can add unlimited website so thats the reason i am giving it a try.
