### ISSUE TITLE
How to send a privilege (item) to several servers on the first attempt?

### ISSUE THREAD

**Issue by braytsar** [WooMinecraft/WooMinecraft#179]
I made one product (Privilege) and want them to go to 2 different servers . If a person buys a privilege (product) it comes only to 1 server for example mini games and the second server does not come Survival . But if, for example, another person on this site will also buy some goods then the first person who bought 2 goods will come his second product . Tell me how to make the person who buys goods for 2 servers got it Instantly?

**Comment by JayWood** [comment]
@braytsar if you download the files here https://github.com/WooMinecraft/woominecraft-wp/tree/feature/dockerize/src this issue should be fixed.

**Comment by JayWood** [comment]
Marking as Fixed see WooMinecraft/woominecraft-wp#47 for further details.
