### ISSUE TITLE
Normalize JSON data

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#18]
Example:
```
if ( empty( $key_db ) ) {
	$json = array(
		'status' => "error",
		'msg'    => "Website key unavailable.",
	);
}

// Better
if ( empty( $key_db ) ) {
	wp_send_json_error( array(
		'msg'    => "Website key unavailable.",
	) );
}
```

**Comment by TekkitCommando** [comment]
Alright, I am getting ready for school once more but will be actively working on this in a few days :) but i am gonna be checking github actively again starting now since im back at a computer :P

**Comment by JayWood** [comment]
I'm not entirely sure how you'd handle the change in java, when I make the change that is, but I know in working with PHP, the JSON will be something like this:
```
//wp_send_json_error( array( 'msg' => 'test' ) );
{
	"success": false,
	"data":
	{
		"msg":"test"
	}
}
```

```
//wp_send_json_success( array( 'msg' => 'test' ) );
{
	"success": true,
	"data":
	{
		"msg":"test"
	}
}
```

**Comment by TekkitCommando** [comment]
Ok, I am sure that Phill and I can figure the java out, I knew in maintaining this project there were gonna be some obstacles here and there :)

**Comment by JayWood** [comment]
@TekkitCommando This is done on the PHP side of things, feel free to close this when the Java is handled.

**Comment by JayWood** [comment]
Also when you're ready, the master branch of the wp plugin is stable, you should be able to do this:
```
cd WooMinecraft/WordPress/minecraft_woo
git checkout master
git pull
cd ../
git add minecraft_woo
git commit -m "Update submodule"
```

**Comment by TekkitCommando** [comment]
Ok Thanks :)

**Comment by JayWood** [comment]
@TekkitCommando I realize you're pretty busy lately, as am I, but when can run the above update to get the WP plugin up to date in this repo?

We should at minimum consider getting the WP up to date before translation is ready due to the JSON changes, you guys will have to change how you're reading it.

**Comment by TekkitCommando** [comment]
Let me talk with my friend Phill :)

**Comment by TekkitCommando** [comment]
@JayWood I have been really busy with making a tech company lately and I will get back to working on this ASAP but for now development on my side will be a little off till mid December sadly :/

**Comment by JayWood** [comment]
This is still an open issue, but MAY be resolve once I finish some code changes on the Java side of things.

**Comment by TekkitCommando** [comment]
@JayWood Sweet, I am also gonna be able to come back to this very soon, I have a config system to redo and some other things to add
