### ISSUE TITLE
i cant use this plugin

### ISSUE THREAD

**Issue by rain931215** [WooMinecraft/WooMinecraft#180]
//////////////////   
// You can delete the following   
// In order for me to better serve your support request, please fill out the following information.   
// Please use pastebin http://pastebin.com/ or gists https://gist.github.com/ for your logs, DO NOT PASTE them in a support request.   
// Refer to the following link for proper config.yml setup fields - https://github.com/WooMinecraft/WooMinecraft#config   
// 
// YOU MUST ACTIVATE DEBUG IN YOUR CONFIG AND PROVIDE THAT LOG
//   
// Fields below this line are required - failure to fill these in will result in your issue being tagged low-priority.   
/////////////////   

**Log Link:** 

### Server Information:
* **Host:**
* **URL:**
* **WordPress URL:**

### Config.yml
* **url:**

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/wiki#create-the-store
