### ISSUE TITLE
Limit per MC Username

### ISSUE THREAD

**Issue by coolty** [WooMinecraft/WooMinecraft#183]
Hello,

I would like to know if there is a way to limit how many times a product can be purchased based on MC username?

Thank you

**Comment by JayWood** [comment]
@coolty as discussed in slack, out of the box this isn't possible. It can be done with some coding. I'll tag as a feature request w/ help wanted - this would be a good first contribution for those wanting something to do.

**Comment by LegalSmeagol** [comment]
I know this is late but I +1 this highly

**Comment by JayWood** [comment]
A few plugins for this:
* https://wordpress.org/plugins/wc-order-limit-lite/
* https://wordpress.org/plugins/maximum-purchase-for-woocommerce/

Just google "WooCommerce, limit purchases" or something similar.
