### ISSUE TITLE
[Enhancement] Add in Pterodactyl Panel support

### ISSUE THREAD

**Issue by spannerman79** [WooMinecraft/WooMinecraft#190]
**Log Link:** N/A - Enhancement request

### Server Information:
* **Host:** N/A - Enhancement request
* **URL:** N/A - Enhancement request
* **WordPress URL:** N/A - Enhancement request

### Config.yml
* **url:**N/A - Enhancement request

I was looking at the updates you were doing with the REST API ( https://github.com/WooMinecraft/WooMinecraft/tree/release/1.2.0 ) so I thought I would ask this.

Would you consider adding in Pterodactyl Panel (https://pterodactyl.io/) support?
They do have an API, and the commands get sent directly to console - so you won't need depend on a plugin or supporting `x` MC version.

There *was* another project that started something like this but they have slowed down due to "lack of support from the community due to other providers" mostly being Tibex (_I suspect, gut feeling_).

WooMinecraft will then be able to support any game server in Pterodactyl as the commands will be ran in console.  A list of possible game servers (eggs) can be viewed via https://github.com/parkervcp/eggs plus others that you can make yourself ( https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html )

List of links:

- Discord: https://pterodactyl.io/discord
- Web: https://pterodactyl.io/

**Comment by JayWood** [comment]
I'll take a look, but this would more than likely be an addon/another project entirely depending on what the pterodactyl API looks like.

Either way, sounds super interesting!

**Comment by spannerman79** [comment]
Thanks for that @JayWood 

I was trying to track down some API docs but it seems with the new `v0.8` release that is being planned they are opening up more endpoints for the panel.  Prob best way is to drop into their discord and ask.

Right now their SSL cert is invalid and they have HSTS so its impossible to view/search

**Comment by JayWood** [comment]
Closing this as wont-do.
