### ISSUE TITLE
/woo check & automatic checking error

### ISSUE THREAD

**Issue by Relaxo143** [WooMinecraft/WooMinecraft#191]
I have a problem when performing /woo check or when the server automatically does it. I'm very new to websites, woocommerce and this plugin so I might be doing something wrong. Excuse my lack of knowledge on the subject. Any idea how to get the plugin working?

**Log Link:https://pastebin.com/W2CTKHHz

### Server Information:
Host: https://infinityfree.net
URL: http://bitcraftstore.epizy.com
WordPress URL: http://bitcraftstore.epizy.com

### Config.yml
url: "http://bitcraftstore.epizy.com"

**Comment by JayWood** [comment]
Issue is here:
`[16:37:10 INFO]: [WooMinecraft] Content Body Snippet (128 chars): <html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,func`

Your host is using a redirect to push users to another page before validating the request. It's a server-side bot-check which some cheap hosts do, you cannot do that when using a JSON endpoint, or any endpoint for that matter.

You'll need to contact your host concerning the redirect, here's it in action:

![](https://i.gyazo.com/fee3d6c19a67ec3d07e27941549db5d1.gif)

**Comment by spannerman79** [comment]
> Your host is using a redirect to push users to another page before validating the request. It's a server-side bot-check which some cheap hosts do, you cannot do that when using a JSON endpoint, or any endpoint for that matter.

I doubt it - look at their responce @JayWood https://forum.infinityfree.net/t/extra-javascript-in-response/7031/3

> All clients using your hosting account must be able to execute javascript responses and accept cookies. Normal website visitors are search engine crawlers are not affected by this, but it does mean that API access is not support here. If you want to host an API service, you’ll need to upgrade your account.

They consider using a direct json feed "API access".

**Comment by Relaxo143** [comment]
Thanks for the information. Would setting the new (redirected) url in the config file help? I used some online tool to check for redirects and it said my site had none but apparently it has one. It's a free hosting solution so I expected there would be some catches/difficulties with it.

**Comment by JayWood** [comment]
I couldn't say, every host handles those redirects differently. I realize why users use free hosting, I use to as well, but GoDaddy has hosting for just 5 bucks a month. One donation should cover that cost really.

At scale, no I won't recommend them, but it's great for getting started.

Add to that, what @spannerman79 said above, you're going to have problems when I release the latest version, which deprecates this `?wmc_key=xxx` custom endpoint in favor of the WordPress core JSON api.

Honestly NO host should be blocking that, and if so, I would look to find another host ( opinion obviously )

**Comment by spannerman79** [comment]
> Would setting the new (redirected) url in the config file help?

@Relaxo143  No it wouldn't.  Even when you try to access a 404/non existant file that is with InfinityFree they inject their javascript (`aes.js`) into the html body.

Personal Opinion:

To get your foot in the door so to speak there are several shared hosting services being and in no particular order;

- GoDaddy
- DreamHost
- A2 Hosting
- BlueHost

But at the end of the day it is better to know how to setup LEMP/LAMP on a VPS.  If you don't want to go through with setting up LEMP/LAMP there is ServerPilot that you can setup on a VPS.  There is also https://nginxconfig.io if your not sure how to setup vhosts for nginx.

There are plenty of options besides "free" hosting that are low cost to start with - just takes some time and/or money to get started.

**Comment by Relaxo143** [comment]
Thank you guys. I moved to another host and solved that problem, but now /woo check doesn't detect that there has been a purchase made. The status of order in woocommerce is "completed", but /woo check spits out `[15:20:25 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":[]}
[15:20:25 INFO]: [WooMinecraft] No data to process, or data is invalid.`
It'd be great if you could help me with that too. I don't use cloudflare or anything similar. And one more thing. Why did you make it so that only premium players can use it? That's a really bad idea in my opinion because now I'd have to handle non-premium account purchases manually. Really makes no sense. Why would you bother to tinker with the mojang api when you can just parse the string to the %s thing and make it work that way?

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft/issues/113#issue-176048209

**Comment by JayWood** [comment]
@spannerman79 don't think that's related, as if the account isn't valid from Mojang, the purchase simply won't go through.

**Comment by JayWood** [comment]
@Relaxo143 Make a new order just in case and ensure an item in the order has commands attached to it. Once you do go to your site's JSON feed and post the data here. The url will be something like: `http://example.com?wmc_key=XXX` where XXX is your server key.

**Comment by Relaxo143** [comment]
> @Relaxo143 Make a new order just in case and ensure an item in the order has commands attached to it. Once you do go to your site's JSON feed and post the data here. The url will be something like: `http://example.com?wmc_key=XXX` where XXX is your server key.

I tried with another order. Still not working. this is the json feed `{"success":true,"data":[]}` I see the same thing in the minecraft console after doing /woo check. The item has 2 commands, is set to virutal and downloadable.

**Comment by JayWood** [comment]
Ensure the order is marked as 'complete' in the admin.

**Comment by Relaxo143** [comment]
Yeah both the previous and the new order I made are with "completed" status.
