### ISSUE TITLE
Issue does not work

### ISSUE THREAD

**Issue by c0mradeteam** [WooMinecraft/WooMinecraft#192]
Log Link: https://yadi.sk/i/wXSN-OB6A5Q0dQ

Server Information:
Host:  cubacraft.su:25565
URL: https://cubacraft.su/
WordPress URL: https://cubacraft.su/

Config.yml
url: https://yadi.sk/d/3I5hF9UX0i-eow

Full list of all my actions:
https://cubacraft.su/wp-content/uploads/2019/03/config.pdf

As if I did not try, the commands on the server do not work :(

My firewall
https://yadi.sk/i/bhGkqvKOdnA_5w
https://yadi.sk/i/pNtAe0VbTwW1IQ
https://yadi.sk/i/Z8PLsAn241TPuQ

**Comment by JayWood** [comment]
Orders must be set to complete in order for commands to send. You don't want charge-backs or pending orders to not send commands, looking at your server, the list is empty for commands which implies there are none pending.

`https://cubacraft.su/?wmc_key=sdfsadfsadfsadfsadf`

**Comment by c0mradeteam** [comment]
Thanks for the help!
