### ISSUE TITLE
/woo check Gives an error.

### ISSUE THREAD

**Issue by Roquex02** [WooMinecraft/WooMinecraft#195]
When I type /woo check it gives to following error. Also packages cannot be deliverd to the server.
11.07 20:03:11 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:887)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:894)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510)
11.07 20:03:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670)
11.07 20:03:11 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
11.07 20:03:11 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
11.07 20:03:11 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
11.07 20:03:11 [Server] Server thread/WARN at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:28)
11.07 20:03:11 [Server] Server thread/WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:124)
11.07 20:03:11 [Server] Server thread/WARN at com.plugish.woominecraft.Util.RcHttp.request(RcHttp.java:50)
11.07 20:03:11 [Server] Server thread/WARN java.lang.Exception: Status code is not 200 got: 503
11.07 20:03:11 [Server] Server thread/WARN Status code is not 200 got: 503
11.07 20:03:10 [Server] Server thread/INFO Roquex issued server command: /woo check

**Comment by JayWood** [comment]
Please fill out the ticket correctly, details are provided when you open a new issue, don't blindly delete it and fail to read please.

Also note the actual error:
> 11.07 20:03:11 [Server] Server thread/WARN java.lang.Exception: Status code is not 200 got: 503

Status is http 503, means server unreachable or it's simply broken on your WordPress side somehow. review your server configuration and verify you can actually access the website, double check configs, etc...

Closing this ticket as it's a service issue from your side, the exception should happen. If you open another ticket please follow the instructions I've taken the time to write down.
