### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by Azorahh** [WooMinecraft/WooMinecraft#196]
Woo just isnt sending commands, I tried resending donations - changing url in slight ways - completing orders - just nothing happening
**Log Link:**
https://pastebin.com/d7QYAEj6

### Server Information:
* **Host:** play.cobbocraft.com
* **URL:**  http://www.cobbocraft.com/shop/
* **WordPress URL:** http://www.cobbocraft.com

### Config.yml
https://pastebin.com/61ubmjEb

**Comment by spannerman79** [comment]
When you created this issue you would have had some commented text that I assumed you didn't read as within that text it had the following;
```
// YOU **MUST** ACTIVATE DEBUG IN YOUR CONFIG AND PROVIDE **THAT** LOG
```
The log you provided doesn't show WooMinecraft debug messages

**Comment by JayWood** [comment]
From what I can tell of what you've provided, the commands are indeed present. However, as @spannerman79 noted, your debug is set to `false` and we need that enabled to check properly.

In the interim, I would ensure that your OVH server can properly talk to your main web server. The servers do not appear to be hosted/routed through Cloudflare so that's good.

**Comment by Azorahh** [comment]
My bad I will enable debug now

**Comment by Azorahh** [comment]
https://pastebin.com/cAk44m4t Ok so I couldn't find it even saying errors but im running things through store - how can I check it can properly talk to my server?

**Comment by spannerman79** [comment]
Create a Test package that does something basic - like makes a broadcast test message, purchase that package (with a cost of 0 obviously) and with debug=true in the config will output whats needed.

That log shows no actual activity - except a final ready time of 27 seconds

**Comment by JayWood** [comment]
Yea, make sure to run `/woo check` with debug set to true. It looks like the plugin was enabled and then disabled, which implies it was set to true and the server was started up just to get the log.

**Comment by spannerman79** [comment]
8 days and no further update - safe to assume [PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC) and to close the issue @JayWood
