### ISSUE TITLE
Extending This Project?

### ISSUE THREAD

**Issue by KingRainbow44** [WooMinecraft/WooMinecraft#197]
This is nothing short of special. This is not a bug report. Just a suggestion. Is it possible that you can expand this plugin to PMMP? (PocketMine-MP) This looks great for my server and BuyCraft is kinda getting old.

**Comment by JayWood** [comment]
I'm not sure what PMMP is, can you send some links my way? Maybe I can if they support plugins and or have an API.

**Comment by KingRainbow44** [comment]
PMMP is PocketMine-MP or a server software for Bedrock Edition. Links: 
https://pmmp.io | https://forums.pmmp.io

**Comment by KingRainbow44** [comment]
Another Feature that I would consider adding would be the ability to send RCON (Remote Console) commands. This way, you can use WooMinecraft for whatever service you like. (even games besides Minecraft that support RCON connections) I wouldn't be able to do this as a pull request since my language is more PHP then Java so coming back to the original question, if you can, make a branch called PMMP and I'll contribute to it.

**Comment by ethsmith** [comment]
Ah that would be really cool for it to support multiple games on Wordpress with RCON.

**Comment by KingRainbow44** [comment]
Finding the command sender in WooMinecraft-WP is the key to implementing RCON. I find that [this](https://github.com/xPaw/PHP-Source-Query) is a key component to implementing the RCON protocol. The issue now is finding where WooMinecraft-WP sends a request to the WooMinecraft plugin.

**Comment by JayWood** [comment]
@KingRainbow44 The WordPress plugin doesn't send anything, the Java plugin polls the JSON API endpoint and runs commands from there. I see something like this being a totally separate implementation and more than likely wouldn't need a JAVA counterpart at all.

What would likely have to happen here is sending the command on order save/complete, if it fails, store it in CRON to be re-ran at a later time. Once ran, remove it from CRON ( ideally a system cron, not WP cron )

**Comment by JayWood** [comment]
Almost 14 days no reply. I'm happy to accept PRs to the java-specific version if necessary, however an RCON implementation will require integration on the PHP side only ( no java plugin necessary ) Feel free to open a PR to the associated repo for PHP if you get that far.
