### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by alantaru** [WooMinecraft/WooMinecraft#199]
I am getting this error when I type woo check in the console.
When I try to give the item purchased via woocommerce panel, nothing happens.
When I type /woo check ingame, nothing happens.

**Log Link: https://pastebin.com/i4AqfpLs**

### Server Information:
* **Host: reishosting.com.br**
* **URL: thornya.pvp.host**
* **WordPress URL: https://thornya.site/loja**

### Config.yml
* **url: https://thornya.site/loja**

**Comment by JayWood** [comment]
[![Screenshot from Gyazo](https://gyazo.com/c6558797086a30e08b65a2b96ca26294/raw)](https://gyazo.com/c6558797086a30e08b65a2b96ca26294)

This is an issue with your DNS server, not the plugin. Unfortunately I've never ran into this issue before so I don't have a fix. I can suggest you go with a reputable host such as GoDaddy, Bluehost, Dreamhost ( I use these guys ) or someone else. 

You can contact your domain registrar and see what's up with the name server configuration maybe.

**Comment by JayWood** [comment]
For what it's worth, after the initial load it loaded fine, but I realized if I changed my IP to a different one using a VPN and flushed my DNS cache via `ipconfig /flushdns` ( windows ) your site failed to load.

**Comment by alantaru** [comment]
Thank you! Ill try to fix that.
