### ISSUE TITLE
Woo Check is returning an Error

### ISSUE THREAD

**Issue by alantaru** [WooMinecraft/WooMinecraft#201]
I have set the key and url correctly, but when I type /woo check i get this error.
Could you take a look what I have missed? Thank you!!

Log Link:-->
https://controlc.com/c0388f5a

### Server Information:
* **Host: thornya.pvp.host**
* **URL: https://serverslist.net/loja/**
* **WordPress URL: https://serverslist.net/loja/**

### Config.yml
* **url: https://controlc.com/38167a30**

**Comment by JayWood** [comment]
For now use the latest pre-release https://github.com/WooMinecraft/woominecraft-wp/releases

**Comment by JayWood** [comment]
Issue is the WordPress plugin version is not correct, only the pre-release supports REST
