### ISSUE TITLE
Not Delivering Products / No Errors

### ISSUE THREAD

**Issue by Alliionart** [WooMinecraft/WooMinecraft#202]
**Log Link:** None (No Errors at this moment)

### Server Information:
* **Host:** SiteGround
* **URL:** https://www.siteground.com/
* **WordPress URL:** https://pandoriamc.com/

### Config.yml
* **url:** N/A?

### Issue
After installing the plugin on both the WordPress side and the MC Server side we sent a test purchase and I was able to receive it fine. The server ran the commands it was supposed to and worked perfectly. After that we added a command onto the test package and we came up with the redirection error code, without changing anything at all. Since then we have tried several URLS:
www.pandoriamc.com
http://pandoriamc.com
https://pandoriamc.com
pandoriamc.com
pandoriamc.com/store
http://pandoriamc.com/?wmc_key=OUR_SERVER_KEY
pandoriamc.com/?wmc_key=OUR_SERVER_KEY

All of these URLs worked and did not give us any errors in the console. We used the /woo check command to make sure and every single time it said no purchases were made when there were orders with 0/1 delivered on the site. We have every package checked as Digital and Downloadable, so I'm not sure what is causing this issue. Any help with this would be greatly appreciated.

We used to have this error but have since fixed the redirection issue. This is an entirely new issue that started.
[OneControlCenter] [01:23:19 WARN]: [WooMinecraft] no protocol: pandoriamc.com/wp-json/wmc/v1/server/Z6GpFu2aSLNtqUsyd8t0
[OneControlCenter] [01:23:19 WARN]: java.net.MalformedURLException: no protocol: pandoriamc.com/wp-json/wmc/v1/server/Z6GpFu2aSLNtqUsyd8t0
[OneControlCenter] [01:23:19 WARN]: at java.base/java.net.URL.[01:23:19 WARN]: at java.base/java.net.URL.(Unknown Source)
[01:23:19 WARN]: at java.base/java.net.URL.(Unknown Source)
[01:23:19 WARN]: at com.plugish.woominecraft.WooMinecraft.getSiteURL(WooMinecraft.java:117)
[01:23:19 WARN]: at com.plugish.woominecraft.WooMinecraft.getPendingOrders(WooMinecraft.java:250)
[01:23:19 WARN]: at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:133)
[01:23:19 WARN]: at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:27)

**Comment by spannerman79** [comment]
More or less your host is performing some sort of host check - see https://www.siteground.com/kb/does_siteground_offer_any_protection_from_my_site_getting_dd/

Contact them to add your MC server to their whitelist/whatever.

**Comment by Alliionart** [comment]
We contacted them and no such check was happening. It is listed just in case, but other wise everything is completely normal without any error codes.

**Comment by JayWood** [comment]
@spannerman79 Look at the first error:
> no protocol: pandoriamc.com/wp-json/wmc/v1/server/Z6GpFu2aSLNtqUsyd8t0

Lack of protocol is typically associated with the fact the user has failed to prefix the URL with a protocol such as `http`, `https`, or hell, even `ftp`

@Alliionart - make sure your URL isn't a relative URL, it has to have a protocol prefix, in fact the default URL should've had that already.
