### ISSUE TITLE
PocketMine server command

### ISSUE THREAD

**Issue by No4NaMe** [WooMinecraft/WooMinecraft#203]
Do I need a plug-in for the PocketMine server to execute commands? or enough that Rcon is turned on and query?

**Comment by No4NaMe** [comment]
Where to get the plugin for PocketMine ?
https://github.com/pmmp/PocketMine-MP

**Comment by spannerman79** [comment]
https://github.com/WooMinecraft/WooMinecraft#important

### This build supports only Minecraft Spigot 1.12.2

Learn to read.

**Comment by No4NaMe** [comment]
> 
> 
> https://github.com/WooMinecraft/WooMinecraft#important
> ### This build supports only Minecraft Spigot 1.12.2
> 
> Learn to read.

https://github.com/KingRainbow44/WooMinecraft-PM/

**Comment by spannerman79** [comment]
Look at the two URLs. Both are from different authors.  

Again - learn to read.

**Comment by JayWood** [comment]
This isn't the place for harsh words or implying that one does not know how to read. Please keep the tickets civil.

Regarding PM - it's not a planned feature. Also I'm not sure why the PM guys want to port the Java code to PHP??? Unless PM uses PHP, or maybe they want to make an RCON only client, which isn't hard.

I'm closing this for now.
