### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by ramdon-person** [WooMinecraft/WooMinecraft#205]
Hi,
I really like this plugin and I used to use it on my 1.12 Minecraft server, but I recently updated to 1.15 and was wondering if (or when) this plugin would be updated.

Thanks a lot!

**Comment by JayWood** [comment]
Have you tried the plugin on 1.15? When I had only a 1.12 build available many reports stated it still worked for 1.14, so it's possible. As for when a new build will be available, not certain at the moment but it's doable.

**Comment by ramdon-person** [comment]
Here is the error I get when I try it on 1.15
![328D53C9-71F1-4754-99C9-C81526B3F65E](https://user-images.githubusercontent.com/48343703/71387548-02d6d580-25ba-11ea-9d53-13e903673294.jpeg)

**Comment by ethsmith** [comment]
@ramdon-person That is an issue with the wordpress and not the plugin I believe.

**Comment by ramdon-person** [comment]
Any suggestions on how I could fix it?

**Comment by spannerman79** [comment]
Well instead of a screenshot supply the actual debug log like stated when you created this issue, for example - I cannot highlight the exact message that shows that the plugin cannot communicate with your wordpress install - ie: file not found.

**Comment by JayWood** [comment]
@spannerman79 the screenshot will suffice

@ramdon-person In the WooCommerce Settings, make sure your server name is `privateKey` it looks like the server key wasn't set up on your WordPress side. Or it's incorrect on the JavaConfig
