### ISSUE TITLE
Donations not being sent

### ISSUE THREAD

**Issue by Jonnyfencing1** [WooMinecraft/WooMinecraft#209]
**Log Link:**
https://pastebin.com/s5r9c9C3
### Server Information:
play.prismmc.co
* **URL:**
prismnetwork.shop

### Config.yml
* **url:**
https://pastebin.com/8g2rRS4e

My issue is that the server donations aren't getting sent, sorry if this is a noob mistake I am a big noob!

**Comment by JayWood** [comment]
HTTP 403 means forbidden. Your Minecraft server cannot communicate with your web server. See these similar tickets: https://github.com/WooMinecraft/WooMinecraft/issues?utf8=%E2%9C%93&q=is%3Aissue+403

**Comment by Jonnyfencing1** [comment]
I've fixed all of that but now no one is receiving their perks ingame

**Comment by JayWood** [comment]
Enable debug and send a log. I can't help you with such a general request 😄

**Comment by Jonnyfencing1** [comment]
What info do you need from it? A log file?

**Comment by Jonnyfencing1** [comment]
Idk what has happened but it appears to be working now, thanks for your help!
