### ISSUE TITLE
I18n all the things!

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#21]
Example:
```
echo 'some string';
// Should be
_e( 'some string', 'minecraft_woo' );
```

**Comment by ApfelUser** [comment]
:+1: Would translate into German :de:

**Comment by TekkitCommando** [comment]
cool :) and ok thanks for the help @JayWood , I was busy like i said but im back :) and feel free to do enhancements when you feel to the development branch, thats what its for :)

**Comment by JayWood** [comment]
@TekkitCommando with me moving the WordPress plugin to it's own separate repo, I'll be able to work there, so no worries.  It's just going to make it 200% easier to manage from a WP Dev perspective.

And it's not a problem, I wanted to help, but with the Java portion of it I'm SO ignorant.  With the WP side of things, since it's my day job, I can at least give you a helping hand there :D

**Comment by TekkitCommando** [comment]
Sweet :smile:

**Comment by brainscript** [comment]
:heavy_plus_sign::+1:

**Comment by JayWood** [comment]
Closing, tracking all WordPress related issues on the [woominecraft-wp repository](https://github.com/WooMinecraft/woominecraft-wp)
