### ISSUE TITLE
Donations not being sent

### ISSUE THREAD

**Issue by ramdon-person** [WooMinecraft/WooMinecraft#212]
**Log Link:**
![1C63307B-464D-452F-96B3-03E723F68265](https://user-images.githubusercontent.com/48343703/78595638-39e69500-77ff-11ea-8c29-b1692295cf0c.jpeg)

### Server Information:
* **Host:** play.voidcitymc.com (version 1.15.2)
* **URL:**  https://voidcitymc.com
* **WordPress URL:** https://store.voidcitymc.com

### Config.yml
* **url:**https://pastebin.com/Xp33zuBR

Donations are not being sent to my Minecraft server. The server is part of a bungeecord network so that might be an issue. Here is my log when I run /woo check
![C2AD0ADD-7CEE-4FFF-92B1-07B523859F1A](https://user-images.githubusercontent.com/48343703/78595732-66021600-77ff-11ea-9a44-65cad535c917.jpeg)
And here is the complicated order in Wordpress.
![E7E4A3CC-500F-457D-989D-2F428410B171](https://user-images.githubusercontent.com/48343703/78596163-24259f80-7800-11ea-94c6-cffc3110d908.jpeg)

Thanks!

**Comment by syzolin** [comment]
Can you leave which branch you are using ? is it bukkit or spigot?

**Comment by ramdon-person** [comment]
I didn't realize that the order had to be set to "completed" status, I added a function that auto completes my orders.
