### ISSUE TITLE
Cannot connect to website

### ISSUE THREAD

**Issue by syzolin** [WooMinecraft/WooMinecraft#213]
I am using Spigot latest Build.
[message.txt](https://github.com/WooMinecraft/WooMinecraft/files/4442872/message.txt)

Cannot connect to my website.

**Comment by JayWood** [comment]
Error: `No subject alternative DNS name matching hyphovy.net found`

The DNS your java server is using to talk to the internet cannot find that domain name, this is a server issue, nothing I can fix.
