### ISSUE TITLE
Woominecraft doesn't have acces to my website

### ISSUE THREAD

**Issue by Samulikoo** [WooMinecraft/WooMinecraft#214]
When I used woominecraft without my page had ssl certification it worked. And when I installed the ssl certification on my website then woominecraft said this when i typed the command / woo check: [03:04:48 WARN]: [WooMinecraft] Server returned HTTP response code: 403

**Comment by JayWood** [comment]
Plugin merely sends the request, how your server responds is not the fault of the plugin, sorry 😞 open a ticket with your host.
