### ISSUE TITLE
[Sponge] Order/Scheduler Issues

### ISSUE THREAD

**Issue by Naccal** [WooMinecraft/WooMinecraft#215]
The Below issue seems to take place during any order check both by person and automated, Can you point me in the right direction to fix this or if you require any additional information, please let me know and i will provide.

Thank you for your time and your great plugin.

**Log Link:**
https://pastebin.com/Zj2Nq8Pm

### Server Information:
* **Host:** Akliz
* **URL:** https://www.akliz.net/
* **WordPress URL:** https://lunarisregion.co.uk/

### Config.yml
* **url:** https://pastebin.com/MqgtrFhz

**Comment by JayWood** [comment]
Unfortunately this plugin is not tested with sponge and should be used with caution.
