### ISSUE TITLE
Give items everytime the plugins update

### ISSUE THREAD

**Issue by ProxTricky** [WooMinecraft/WooMinecraft#217]
https://pastebin.com/9qS0A0jk

### Server Information:
* **Host: ikoula debian9
* **URL: play.satyria.fr
* **WordPress URL: https://www.satyria.fr

### Config.yml
* **url: https://www.satyria.fr

Hi, me again, the plugins now work but not perfectly, everytime the plugin update (15000 seconds) or at any /woo check, the command is send all the time..
I've created a give command to make sure it work and it is but give the product every time it update
Is it a problem with my https so the plugins on my minecraft server can't check if delivery has been done ?
Sorry for my poor english mate!

**Comment by JayWood** [comment]
When the plugin updates, it sends data back to your website to let the site know that it has sent those items. There is an issue on your server ( where your WordPress host is ) that is either not receiving the data, or for some reason the JSON endpoint is cached.

**Comment by ProxTricky** [comment]
could it be because of the ss certificate, or it's someting missing ?
did i need to point the url on the shop url of my wodpress( dumb question cause it might only need the root folder of the wordpress install)

**Comment by JayWood** [comment]
No the latest version uses the rest API, you shouldn't use the `/shop` url anymore.  I would open a ticket with your host and explain to them that the java plugin sends data back to your site in a `POST` request and if they can confirm if the `/wmc/v1/servers/<server_password>` is not cached.

In the admin for the site, do you see the items as delivered? I think I remember adding that as a column in the list view.

**Comment by Aaragon76** [comment]
> No the latest version uses the rest API, you shouldn't use the `/shop` url anymore. I would open a ticket with your host and explain to them that the java plugin sends data back to your site in a `POST` request and if they can confirm if the `/wmc/v1/servers/<server_password>` is not cached.
> 
> In the admin for the site, do you see the items as delivered? I think I remember adding that as a column in the list view.

is there the rest API Key, or the Serverkey inside of this file?

**Comment by firefloc** [comment]
same thing for me with ni host but i've a Cpanel how can I solve the problem?

**Comment by JayWood** [comment]
Server password is the key you set in WooCommerce > Settings at the bottom of the page. You also need to enter that key in your config.yml
