### ISSUE TITLE
file not found?

### ISSUE THREAD

**Issue by beamer91** [WooMinecraft/WooMinecraft#219]
I am running a paper 1.15.2 server and I made sure the keys were the same on both the Wordpress site and the plugin
My Wordpress is a new fresh install.  I have debug enabled and when ever I do woo check in the console I get this error
https://pastebin.com/wSvR8Yf7
I also have tried the site as http:// and https:// in the plugin config and get the same results
I did notice that it seems to be trying to get a file at https://vmc.unknownskies.net/wp-json/wmc/v1/server/privateKey but in the site root folder there is not even a folder called wp-json if that is relevant.

**Comment by JayWood** [comment]
Looks like your host has disabled the REST api for some reason? Contact your hosting company and ask them "What is the URL for my WordPress REST API" 

Typically it's /wp-json/

**Comment by beamer91** [comment]
I am self hosting it. Could you direct me on how to set it up

**Comment by JayWood** [comment]
wp-json is the WordPress rest API base, WoOcommerc extends that, if you can't hit wp-json you can't hit the woocommerce api. The issue is your server configuration or permalinks. That's all I can tell you, the rest you'll have to figure out purely because each setup is different.
