### ISSUE TITLE
Grunt, CSS Min, and Jshint

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#22]
Should setup grunt with the following:
* grunt-contrib-cssmin
* grunt-contrib-jshint
* grunt-contrib-uglify

As well as provide .min.css/js files accordingly

**Comment by TekkitCommando** [comment]
:+1:

**Comment by JayWood** [comment]
Closing, tracking all WordPress related issues on the [woominecraft-wp repository](https://github.com/WooMinecraft/woominecraft-wp)
