### ISSUE TITLE
Is this working on 1.16.1?

### ISSUE THREAD

**Issue by godgutten** [WooMinecraft/WooMinecraft#220]
Im not sure where to ask but is this working on 1.16.1

**Comment by ethsmith** [comment]
Download and try it good sir. The code should be MC independent so basically yes since I don’t believe any major api changes happened.

**Comment by godgutten** [comment]
Okay Im going to test it then when im home next week

Thanks for the fast answer

**Comment by JayWood** [comment]
Closing, personally tested versions are tagged.
