### ISSUE TITLE
[WooMinecraft] java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by ProtoGhost** [WooMinecraft/WooMinecraft#221]
when i type /woo check 
I'm getting this error https://pastebin.com/E9KBam5x
please help me
[message (1).txt](https://github.com/WooMinecraft/WooMinecraft/files/4878627/message.1.txt)

**Comment by JayWood** [comment]
Replied in discord, closing.

For reference, https://discordapp.com/channels/417179313775968289/417367458144452609/729598711105323060
