### ISSUE TITLE
How the Woominecraft Post request work?

### ISSUE THREAD

**Issue by abhiram555** [WooMinecraft/WooMinecraft#222]
Hello,
I would like to know how the post request of woo Minecraft work

**Comment by JayWood** [comment]
- The WordPress REST endpoint contains a list of commands and players for each command. 
- Commands are keyed by WooCommerce Order ID if I recall.
- The Java Plugin contacts the REST endpoint on the interval  you specify ( default every 15 minutes ).
- For each command, the Java Plugin determines if the user is online or not.
- If not, command is not executed.
- If they are, command is executed and the order ID is added to a payload.
- Once all commands are ran the payload is sent back to the WordPress REST endpoint.
- For every order ID received, that order is marked as delivered.

**Comment by abhiram555** [comment]
Okey,Thank you verymuch
