### ISSUE TITLE
[Question] WooMinecraft in version 1.13+?

### ISSUE THREAD

**Issue by jannis6023** [WooMinecraft/WooMinecraft#224]
Hi, I‘d really like to use WooMinecraft in version 1.13 an 1.15.2. Does anybody have experience with these versions? Will there be an update?
Would be pretty nice to use this wonderful Plugin!

**Comment by ethsmith** [comment]
Like other issues similar to this. The plugin is version agnostic as far as tests go.

**Comment by JayWood** [comment]
Closing in favor of #237
