### ISSUE TITLE
FATAL ISSUE HEEEEELP!!!

### ISSUE THREAD

**Issue by pjindras** [WooMinecraft/WooMinecraft#227]
Hi i have an issue aftew wp and woocommerce update, i cant in orders section assign my server, the server is configured well and everythink worked nice and good, but its not working now anymore and i did nothing with it.

see the screen here: https://ibb.co/hFYpRn4

I see only Odstraněno () -> it means in czech removed ()

What to do now? Thanksss

**Log Link: log is ok**

### Server Information:
* **Host: play.hexxcore.eu**
* **URL: https://hexxcore.eu/**
* **WordPress URL: https://hexxcore.eu/**

### Config.yml
* **url: config is ok**

**Comment by ethsmith** [comment]
That is directly from adding/removing servers in WooCommerce settings, Just add it again in settings

**Comment by motherboard1999** [comment]
I have the same issue. Add a new server doesnt work :/

**Comment by JayWood** [comment]
To reproduce the issue:
* Add a server in WooCommerce > Settings
* Create some orders for that server & deliver them
* Delete the server in WooCommerce > Settings

To fix the issue:
* Add back the server with the same key
- or -
* Delete that order and make a new order under the new server manually
