### ISSUE TITLE
[WooMinecraft] Server returned HTTP response code: 400 for URL:

### ISSUE THREAD

**Issue by Plugrol** [WooMinecraft/WooMinecraft#228]
**When i'm trying to perform the /woo check command, it print an exception into the Console.**

**Pastebin**: https://pastebin.com/3HVfYZZ0
**Host**: 147.135.146.38
**URL**: https://www.kissenpvp.de/
**WordPress URL**: https://www.kissenpvp.de/
**config-url**: https://www.kissenpvp.de

_Ps: It doesn't work with the browser either._

**Comment by JayWood** [comment]
Closing due to age of ticket. Plugin is no longer installed on site.
