### ISSUE TITLE
WordPress coding standards

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#23]
Ensure all WordPress code meets the [WordPress coding standards](https://codex.wordpress.org/WordPress_Coding_Standards)

**Comment by TekkitCommando** [comment]
Ok Thanks!

**Comment by JayWood** [comment]
Closing, tracking all WordPress related issues on the [woominecraft-wp repository](https://github.com/WooMinecraft/woominecraft-wp)
