### ISSUE TITLE
Support 1.16.3

### ISSUE THREAD

**Issue by WarenGonzaga** [WooMinecraft/WooMinecraft#230]
I just want ask for the version 1.16.3 is it already supported?

**Comment by JayWood** [comment]
The plugin uses minimal interaction with the Spigot or Bukkit API - I'd be surprised if it doesn't work. That being said, it is untested for 1.16.x as of yet.

**Comment by WarenGonzaga** [comment]
Hi @JayWood I will test it on my server and will let you know.
