### ISSUE TITLE
 Need Feedback - Move WordPress plugin to Submodule

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#24]
Suggest moving WordPress Plugin to a submodule, this allows dev's to clone the wordpress only portion of the repository directly into their `wp-content/plugins/` directory instead of having symlinks and all that jazz since that's not always possible.

If it's okay with the other @WooMinecraft/owners I'll go ahead and do this.  We could still address tickets and issues here, or there, unless you guys have a better idea where I don't have to edit the code under the git repo, then copy it to the WordPress plugin directory.

**Comment by TekkitCommando** [comment]
Yeah thats fine, Phill helps me with things but i do all the consistent development :P

**Comment by TekkitCommando** [comment]
I was a little busy for a few days but im back :)

**Comment by JayWood** [comment]
Awesome, wanted to make sure I wasn't stepping on anyone's toes, I'll do this sometime this weekend.
