### ISSUE TITLE
[Bungeecord Support] will there be bungeecord version? 

### ISSUE THREAD

**Issue by Cenastor** [WooMinecraft/WooMinecraft#247]
Are there any plans to add a bungeecord version? I'm switching from a single server to a network server with atleast 3-4 other servers. It would be real handy just to add the plugin to my proxy server and have it send commands to the different servers. 
I noticed there was a issues with the bedrock "*" prefix I'm also having the same issue because I'm running a geyser install that allows Java and bedrock to play together can't wait for that to be pushed out.

**Comment by jerzean** [comment]
as far as the author has said  there will not be a Bungee version, they only way is to add it to each server, which i have tested and done myself before and it works
