### ISSUE TITLE
Wordpress cannot send commands.

### ISSUE THREAD

**Issue by OverBrave** [WooMinecraft/WooMinecraft#253]
![image](https://user-images.githubusercontent.com/47111280/144210534-5a57e4fe-6a77-4333-93c5-e339806ae54d.png)
![image](https://user-images.githubusercontent.com/47111280/144210577-f09a8b1f-e903-4e0c-a6a7-2b0bc11c6228.png)
![image](https://user-images.githubusercontent.com/47111280/144210785-d471fc57-1fdb-467f-9cea-ce190875f5fb.png)
It doesn't send the command even when I click on it. What exactly is the problem? I am using Wordpress version 5.8.2

**Comment by JayWood** [comment]
Summary for anyone looking in the future. Player must be online for commands to send.
