### ISSUE TITLE
problems with the plugin

### ISSUE THREAD

**Issue by 2006lev-Web** [WooMinecraft/WooMinecraft#266]
![Screenshot_13](https://user-images.githubusercontent.com/64630503/153356009-3d8babb7-9cac-45b0-b1d1-a511a4ba83b3.png)
![Screenshot_12](https://user-images.githubusercontent.com/64630503/153356011-f1bd99d2-7208-404c-b79d-eeb796a752d3.png)
  bungeecord: true
online-mode=false
when I write this command I get an error how to fix it
I have BungeeCord installed server version version 1.16.5
![image](https://user-images.githubusercontent.com/64630503/153356574-29f8b9bf-7965-4ab3-9866-aa1856c48274.png)

**Comment by JayWood** [comment]
Must install WordPress plugin and maybe set the new config `prettyPermalinks` to false in java config.

**Comment by 2006lev-Web** [comment]
![image](https://user-images.githubusercontent.com/64630503/160169459-cd82c4f1-8d9d-47b5-b38d-73e24ed7a4d0.png)
I have 1 more problem

**Comment by JayWood** [comment]
A logic fix is opened to fix this in #271 should be merged and released this week ideally.
