### ISSUE TITLE
Problems with rest api connections

### ISSUE THREAD

**Issue by Cerexus** [WooMinecraft/WooMinecraft#274]
Hello,

I got some problems with the rest api. 
If i do /woo ping i get every time a timed out exception for the rest api and sometimes a timed out exception for the server connection. 

Maybe my Server is too slow? I don't know.

If i open this link manually 
https://cubetales.de/wp-json/wmc/v1/server/key 
then i get {"orders":[]} as response. 

I tried to activate and deactivate pretty links in the config, but had no luck with it.

**Comment by Cerexus** [comment]
Finally i got the connection... 

Woominecraft-wp registers v1:
function get_rest_namespace() {	return 'wmc/v1';}

Woominecraft tries to use v2 with default settings:
"/wp-json/wmc/v2/server/";

Maybe i missed something else in the code.

**Comment by JayWood** [comment]
That shouldn't be, will look.

**Comment by JayWood** [comment]
Wow that's a hell of an oversight on my part... damn :( 

Rest API is v2 in java code - https://github.com/WooMinecraft/WooMinecraft/blob/main/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L140

But is registered as v1 in WP code - https://github.com/WooMinecraft/woominecraft-wp/blob/93f36d32ccd70246219cbbd897ac7663559df67c/includes/rest-api.php#L25

Java plugin needs updating 😢

**Comment by Cerexus** [comment]
No worries
