### ISSUE TITLE
Issue with rest api connections

### ISSUE THREAD

**Issue by asullivan2000** [WooMinecraft/WooMinecraft#276]
**Log Link:**
https://pastebin.com/eg0PaLzP (Tried to hide security code but failed)
### Server Information:
* **Host:**: Just Simple Hosting
* **URL:** https://www.jshosting.co.uk/
* **WordPress URL:** https://our-mc-server.jshosting.co.uk/
* Jar type and version: 1.18.2 paper.jar 
* MC Server: mc.jshosting.co.uk

### Config.yml
* **url:**
https://pastebin.com/J8pEyHdY

### Replication steps
1. Go to console
2. Run command run /woo ping
3. Look at the failed api request.
4. When entering the url outputted from console it shows: {"orders":[]}
(Replicated here: https://i.imgur.com/rU6itGL.gif )
5. I've tried downgrading to 1.4.4 but that was before the api fix. 1.4.5 or 1.4.4 don't work.

**Comment by JayWood** [comment]
`21.04 13:52:37 [Server] ERROR [WooMinecraft] no protocol: /wp-json/wmc/v1/server/rx8TtUnQVtUxe9Vr` are you overriding the REST base URL? if so, you need to use the full URL and include a protocol - `https://` for example - URLs must be a URL not a relative path.

Also don't worry about the security code ( I mean change it yea ) but the only thing someone can do with it is 'complete' an order. Outside of that, it has no use.

**Comment by asullivan2000** [comment]
Thanks JayWood,
I resolved the issue, I still get an API time out when running /woo ping but /woo check gets the orders. So all working as intented.
Thanks for the quick response JayWood.
