### ISSUE TITLE
New Config is OCD

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#28]
I will fix this but as of now it doesn't like key starting out as empty :P

**Comment by TekkitCommando** [comment]
I guess the best way to do this is to set the key to "changeme" and then have a key check so we can tell them to use /woo register

**Comment by TekkitCommando** [comment]
New Issues Arose... I fix lol

**Comment by TekkitCommando** [comment]
@JayWood I fixed some of the code I made a stupid mistake on that may have caused the config reset bug, I am not sure yet though, I will be testing it soon :)

**Comment by JayWood** [comment]
@TekkitCommando We need a nightly build branch, every time you make a change, I'd like it if you could push it there, so we're all 100% up to date.

I don't mean literally every letter you type of course, mainly when you sign off ( stop working on the plugin ) even if it's broken, it'd be great to push it up to a sort of 'unstable' branch.

**Comment by TekkitCommando** [comment]
Ok I will make a new branch called dev-nightly

**Comment by TekkitCommando** [comment]
Made it

**Comment by JayWood** [comment]
Closing, working on config changes.
