### ISSUE TITLE
Could not initialize class okhttp3.OkHttpClient

### ISSUE THREAD

**Issue by Stormez1998** [WooMinecraft/WooMinecraft#283]
Hay i open a ticket before but that is fixed and i open a New ticket for a new issue.

After its working and i make a purchase in the shop, the Server recive that Info and give me the item as expected.
But in console (bcs i have debug on) it says this:

![image](https://user-images.githubusercontent.com/57358176/181875072-86281dd0-780f-4c72-899a-f7eca3d7c857.png)

> `[06:46:27] [Craft Scheduler Thread - 40/WARN] [com.plugish.woominecraft.WooMinecraft]: [WooMinecraft] Plugin WooMinecraft v1.4.5-1.8.8 generated an exception while executing task 16462
 java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient
	at com.plugish.woominecraft.WooMinecraft.sendProcessedOrders(WooMinecraft.java:250) ~[?:?]
	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:233) ~[?:?]
	at com.plugish.woominecraft.BukkitRunner.lambda$run$0(BukkitRunner.java:18) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:1.12.2-df5e909d]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:1.12.2-df5e909d]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:1.12.2-df5e909d]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]`

So i guess the MC plugin cant send the Information back to the Wordpressplugin. But bcs wordpress is not reconize any answer that the item/s delivert it will send them every time i do /woo check or when i have set the update_interval to for example 30 sec it will give me the Items every 30 secs. When i delete my Order the plugin says that there are no more Orders, so hes Reconise that.

Any Help pls.

**Comment by jerzean** [comment]
paper is a stripped version of spigot made for performance, the api used to send the info back to the website isnt included with paper, thats why you have this error, the 
`java.lang.NoClassDefFoundError:`
thats the dead give^^^

**Comment by Stormez1998** [comment]
So i have o use original spigot? Bcs i use Magma (Plugins and Mods)

**Comment by mercurialmusic** [comment]
> paper is a stripped version of spigot made for performance, the api used to send the info back to the website isnt included with paper, thats why you have this error, the `java.lang.NoClassDefFoundError:` thats the dead give^^^

Paper is the leading Minecraft server platform, with now [more than double](https://bstats.org/global/bukkit) the users of Spigot (even when not counting Paper forks), so it would at least make sense to play nice with it. I came here to check out the plugin since I'm really not a fan of BuyCraft and want to move away from it, but I have to admit this makes me hesitant.

**Comment by jerzean** [comment]
> > paper is a stripped version of spigot made for performance, the api used to send the info back to the website isnt included with paper, thats why you have this error, the `java.lang.NoClassDefFoundError:` thats the dead give^^^
> 
> Paper is the leading Minecraft server platform, with now [more than double](https://bstats.org/global/bukkit) the users of Spigot (even when not counting Paper forks), so it would at least make sense to play nice with it. I came here to check out the plugin since I'm really not a fan of BuyCraft and want to move away from it, but I have to admit this makes me hesitant.

try it with paper first, didnt know they was using magma, which we will never support

**Comment by JayWood** [comment]
The plugin is opensource, you are free to fork it and hire a developer to build it.

>  it would at least make sense to play nice with it

There is no value for me in building for a platform which I do not currently utilize.
