### ISSUE TITLE
WooMinecraft Translated by Language Files

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#29]
Instead of a messages.yml file it will us a language file such as english.yml, german.yml, spanish.yml and you can set the language file name in the config :)

**Comment by HappyHarm** [comment]
Is there already a format for this? Then I will start adding a dutch language file :P

**Comment by TekkitCommando** [comment]
not yet, i will add one to the wiki :)

**Comment by JayWood** [comment]
Duplicate of #25 closing that one merging here.

**Comment by JayWood** [comment]
Fixed as of above commit, closing.
