### ISSUE TITLE
Bukkit Plugin is Terribly Organized

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#3]
The Java Side of Woo Minecraft is terribly organized and so I will reorganize it before fixing bugs :)

**Comment by JayWood** [comment]
This is what happens when you get a Java noobie like me coding Java :D 
I wish you the best in working with the Java portion of it, I myself wanted to update it, but haven't had the time to work on my java skills.

**Comment by TekkitCommando** [comment]
Ok thanks, I am glad that you are ok with this :) I was kinda worried you might think I was stealing your thunder since it was your plugin xD @JayWood

**Comment by TekkitCommando** [comment]
@JayWood I sent you an invitation to the owners group so you can always join in whenever :)

**Comment by JayWood** [comment]
Not worried at all, hope it goes well, if you need some WordPress help with it I'm your guy, but my java skills are definitely lacking.

**Comment by TekkitCommando** [comment]
Ok :)

**Comment by JayWood** [comment]
My one and only request, keep the code GPLv2 so others may copy it at their leisure!

**Comment by TekkitCommando** [comment]
Oh ok sorry will change that now, I must of read v3 wrong thought It was just a more up to date version of v2 xD

**Comment by JayWood** [comment]
I didn't even read it haha, I just know that all my code is GPLv2 compatible

**Comment by TekkitCommando** [comment]
Oh ok so I might be right but I will change it back xD Also to reduce the amount of kids saying I submitted jars without your permission could you join this organization? I understand if you would rather not :)

**Comment by JayWood** [comment]
I sure can!

**Comment by TekkitCommando** [comment]
Thanks! :)

**Comment by TekkitCommando** [comment]
I think the organization is fine, might need a little tweaking but not much
