### ISSUE TITLE
WooMinecraft Official Release Info

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#30]
Hi Everyone! The Woo Minecraft Team has been trying to juggle Life, Woo Minecraft, Work, and Possibly school, which can be a pain at some points but I am pleased to tell you that I am almost ready to upload the new and finished Config and Message system code, which was one of the final things we needed before releasing an official alpha version of Woo Minecraft for the public to download and have on production servers. Below is a list of things we have added, modified, or fixed and included in the Alpha Version.

Fixed:
* Null Key Bug
* getOnlinePlayer list bug
* args.length command bug

Modified:
* Main Class Init Format
* Key Generation Code
* Command Format
* Complete WordPress Code

Added:
* New Config System
* New Message System

**Comment by JayWood** [comment]
The WordPress sub-module has not been updated to the latest stable WordPress release, we should make it a point to do that and compensate for the new JSON result set in the Java code if possible.

Also, this is the first time I've seen GitHub issues used as a sort of `bulletin` system.  I believe we should consider making a changelog file instead if you want users to keep up to date with recent changes, or you can follow the WordPress way ( sorta ) and include a changelog section in the readme.md similar to my [Content Warning](https://github.com/JayWood/content-warning-v3) plugin.

**Comment by TekkitCommando** [comment]
ok i planned to update this as we added stuff but yeah i like your idea :)

**Comment by JayWood** [comment]
@TekkitCommando you can always link your website as well, and provide updates there :D

**Comment by TekkitCommando** [comment]
True ok
