### ISSUE TITLE
I am back

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#31]
Sorry I am creating a Software/Game Development LLC and so have been busy I am gonna start working on this again in the next few days

**Comment by TekkitCommando** [comment]
My computer is taking longer to be fixed then i thought, I am sorry :/

**Comment by HappyHarm** [comment]
:s is there already a multiserver/bungee version btw?

**Comment by TekkitCommando** [comment]
No bungee plugin but we can add that to the list :)

**Comment by TekkitCommando** [comment]
Just got my computer :)

**Comment by TekkitCommando** [comment]
Ok I am getting the JDK and my IDE installed and then getting back to work on ol' Woo Minecraft
