### ISSUE TITLE
New Update Coming Soon!

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#32]
Sorry I have been gone because of computer problems and other life things but most of my computer issues are fixed and so I just wanted to let you guys know that there will be another update in the coming weeks as I get back into my programming routine :D Sorry I cant post these updates on my site rn :/

**Comment by HappyHarm** [comment]
Welcome back then :smile:

**Comment by TekkitCommando** [comment]
Thanks :D

**Comment by HappyHarm** [comment]
Is there still someone working on this?

**Comment by TekkitCommando** [comment]
I got very busy with school and life in general and so is Phillmac and the creator as well. I am still working on it every once in a while but I will need till after Christmas before I get back into full development @HappyHarn

**Comment by TekkitCommando** [comment]
@HappyHarm *

**Comment by JayWood** [comment]
@HappyHarm if I can be of any help by all means just post a message.

**Comment by TekkitCommando** [comment]
Assuming all goes well, I can work on Woo Minecraft in a couple weeks when Christmas vacation has started and I'm off school. Maybe sooner then that :)

**Comment by TekkitCommando** [comment]
@JayWood sorry for leaving the project inactive for this long, I made it my responsibility to revive and maintain this system and i let you down and @HappyHarm I am sorry for letting you and the rest of the people waiting for this down. My life has gotten very busy but I am gonna try to spend more time with Woo Minecraft, it's like my baby now xD

**Comment by HappyHarm** [comment]
Np, I'm just following this project sometimes :P

**Comment by JayWood** [comment]
@TekkitCommando It's cool m8 - I actually picked up some java skills since last time we met. I've also successfully setup the project w/ Maven and I'm making some changes of my own - though so VERY slowly.

Additionally, I found quite an easy way to implement the translations system you spoke about in Issue #29 Taking an idea from the WordPress i18n and l10n book of course!

I'll be doing this work on a separate branch as to not break any code you've already written, so no worries there.

**Comment by TekkitCommando** [comment]
@JayWood Alright cool, I will have my code still beign pushed to the development branch, I took off some things and so should be able to start on this again a lot quicker and start rolling out updates. Interested in seeing your changes :)
