### ISSUE TITLE
Donations Signs & GUI's

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#34]
@JayWood 

This is more for the future considering we still haven't gotten web purchases to communicate with the Minecraft server 100% correctly yet but I was wondering if you had an idea how we will get the packages from the web server and list them via GUI and Sign?

**Comment by JayWood** [comment]
Not sure what you mean by packages? The WordPress plugin allows you to specify multiple commands for either a single product, product variation, or both.  The former being ran first.

So in theory, a package is just a single item with multiple commands.  You can theoretically add an unlimited amount of commands to a single item, and are only limited by what Bukkit/Spigot can parse - maximum memory essentially.

As for the GUI - are you talking like a full fledged in-game popup gui, or something similar to other large scale projects, a text-based system which shows up to only the single user?

I might have an idea of how to do the text-based chat system, but as for a full fledged GUI I'm not entirely sure.

As for signs, it's possible, but needs to be fully thought out.  There are obvious questions that arise like the following:

* Do we want the user to be able to purchase directly in game?
* If so - that leads to a 'deposit' system - which leads down the rabbit hole of financial withdraws etc...
* Should the signs simply open a link or prompt a user to open a link to a product?
* How will we handle items with long titles?
* Plenty more I could think of, but you get the point!

**Comment by TekkitCommando** [comment]
It would probly be best to have it generate a link to the product picked off the sign or gui. I have never seen a plugin actually able to take purchases ingame

**Comment by TekkitCommando** [comment]
Not package, a product xD

**Comment by JayWood** [comment]
Did a little digging here.  From what I can tell the click dialog itself "open this link" is client side, not server-side, and therefore cannot be interacted with.  

However, we can definitely send them a link to the product in chat.  I envision a scenario like this:
* Admin places a sign
* Sign text reads [woo #]
* # Should match item ID from the WooCommerce side of things ( WordPress Dashboard )
* Sign hits the server, requesting product title.
* Sign is updated with product title
* We store the product title in the block/entity's meta data [something like this](https://www.spigotmc.org/threads/meta-data-on-placed-blocks.55072/)

Down the road
* Player clicks sign
* Sign sends PM with link to product

**Comment by JayWood** [comment]
Slated for a later release.
