### ISSUE TITLE
getPlayer() Deprecated

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#36]
getPlayer() is deprecated, but is used in the development code ( haven't looked at master ).  Will need to update to getUUID() instead.

In-turn, this means that the WordPress side of things.  Will need to add the Minecraft UUID to the WordPress data as well as a time-stamp.  Refer to [Mojang's API](http://wiki.vg/Mojang_API)

**Comment by TekkitCommando** [comment]
@JayWood It will still work, its just not recommended so not too many worries but still should be changed :)

**Comment by JayWood** [comment]
@TekkitCommando I'm aware it will `work` but in keeping with standards, any/all deprecated code should be updated if we have the ability :smile:

**Comment by TekkitCommando** [comment]
@JayWood I agree :P

**Comment by TekkitCommando** [comment]
@JayWood Wouldn't inefficiency better fit this issue? :P

**Comment by JayWood** [comment]
Feel free to re-tag it, i've not looked through all of the tags you created for this project, I just grabbed the first two :smile:

**Comment by TekkitCommando** [comment]
@JayWood lol nice

**Comment by TekkitCommando** [comment]
I think today after school I can work on changing to UUID :+1:

**Comment by TekkitCommando** [comment]
After I add the UUID change I can compile a jar and add another pre alpha release :)

**Comment by JayWood** [comment]
Sweet, I'm making changes on the WordPress side to store the UUID and timestamp of the purchase, alongside the username.  I'll update the code accordingly.

**Comment by TekkitCommando** [comment]
My IDE was acting up today but tomorrow I will start making changes in the dev-nightly branch

**Comment by mmuziek** [comment]
em may i say something.
if you do this be noticed that it doesnt work on bungeecord anymore if its not toggleable

**Comment by HappyHarm** [comment]
@mmuziek what do you mean with not toggleable? What should be toggleable?

**Comment by mmuziek** [comment]
well the use of uuid
because if i make use from a bungeecord instance it gets FAKE uuids not the real ones
if this plugin catches uuid and uses them then people wont get their stuff...

**Comment by HappyHarm** [comment]
Ah you mean like if we're getting the premium UUID's with the plugin, they will be totally different from the UUID's that the bungee generates. 

Only I thought that if bungee is online mode it will not generate fake UUID's. But it's the authors (@JayWood) choice to allow cracked servers as well.

**Comment by TekkitCommando** [comment]
Honestly @JayWood and I will probably not support unpaid accounts and cracked servers. I can't speak for JayWood but I'm sure an issue popped up somewhere (I think the uuid system issue) where he said he didn't plan to.

**Comment by JayWood** [comment]
We will not support cracked/offline servers. The reason behind this is simple, if the players on a server, can't be trusted to buy a game, why would you trust them to donate to your server?

Until I can find a legitimate reason to support offline servers that outweighs possible piracy, I cannot see a reason to support offline mode.

**Comment by mmuziek** [comment]
well bungeecord is in online mode but the subservers arent. thats the problem.
i recommend to use name verification instead of uuid like all other webshops do.
otherwise you abandon like 45% of all servers

**Comment by HappyHarm** [comment]
@mmuziek Yeah but the subservers get the UUID from the bungee right? And when the bungee is online mode true then the subservers should get the online mode UUID's as well.

**Comment by TekkitCommando** [comment]
@HappyHarm Bungee should produce real online UUID's if online mode is on. If it doesn't I am sure there are work arounds that we can consider. Minecraft is $26 and totally worth the payment. We aren't really worried.

**Comment by HappyHarm** [comment]
@TekkitCommando That's what I ment yes ;) I'm not running cracked by myself and I agree that it is worth the money but my server started cracked (when I was still cracked as well) and when I bought it switching to premium would mean to lose everything (because of that fake UUID's) :S

**Comment by TekkitCommando** [comment]
Yeah.. What I will do is probably try to figure out a way to check if there is a bungee cord instance and that is the only time it will collect offline uuids. I am not sure how plausible that is or if @JayWood has a different idea but that's what i am thinking atm.

**Comment by JayWood** [comment]
@mmuziek I understand your point of 'doing what all the other guys do', but well, we're not the 'other guys'. I fully stand by my 'not supporting offline servers' statement. Also, please don't tell me that 45% of ALL Minecraft servers are ran by Bungee, if you're going to provide statistics, at least link some sources.

Perhaps my confusion is purely around how bungee works, if for instance you MUST have all sub-servers in offline mode, then yes, I understand that may be a problem, but, having a server in offline mode, at least from my experience since MC Pre-Alpha, opens your server up to non-verifiable users.

I apologize if this reply comes off harsh, it's just that `offline mode` gets my blood boiling!  There are ways around this, if you're a WordPress ninja like myself, but none of which I will divulge.

**Comment by mmuziek** [comment]
woa i did not say anything offensive.... well atleast i tried to not being offensive

anyways my bungecord is in online mode my subservers in offline with a whitelist function connected to the bungecord proxy this how many servers protect their network from unverified users
so i do get verified by bungee but i get an other uuid then when i host a spigot server alone.
thats the problem in this case.

so giving items and rank through this plugin is only possible using the name of the player.
and not the uuid.

i hope you understand my matter. i dont care if you check if  its a valid minecraft account i do care that the commands do not get replaced by uuid because then everything breaks from plugins to the bungeecord server

**Comment by HappyHarm** [comment]
@mmuziek are you sure about that. Really thought that the fake uuids were only for servers that are running their bungee in offline mode.

**Comment by mmuziek** [comment]
well its true.
this is my real uuid a43e151b-3dae-4521-****-c1e8848e1964
this is the uuid i get from bungeecord:  0db8671f-bfa5-30fd-****-a16060d5a763

**Comment by JayWood** [comment]
@mmuziek Not sure why you'd hide your UUID, it's openly available from the mojang API, I only need your username :imp: 

And no, you said nothing offensive, i was merely apologizing if I came off harsh.

First, thanks for explaining this in detail.  I wasn't aware that you could setup bungee in that way, hell I don't even know what bungee was good for outside of a server host.

With that being said, it would seem that we need to find a way of delivering items that would work in your scenario.  The problem is that `getPlayer()` is deprecated, which means it may be removed in the future, or near future. So, even if we keep it now, we WILL have to remove it down the line. 

Therefore, I believe we need to figure out how Bungee is producing these fake UUIDs and see if there's a method we can tie into. The problem we're going to have, is that the WordPress plugin ( at least my plan is ) will store the player name and UUID from mojang's API, and when the server reads the JSON data, it's keyed by UUID, not player name.  Yes we can send the name along with the UUID to the server and let the server decide which to use, but I'm insanely against an offline_mode server.

So, I have some questions:
* Is there no way to turn your other servers into online mode?
* How does having an authorization proxy give you more benefits than just using online mode?
* Is this `Bungee` setup an edge case, or is it a standard that would warrant us allowing offline mode?
* If it is a standard, I'd rather code a Bungee specific version and put some requirements in place to make 100% sure you have this sort of setup, to ensure 100% that it's being used legitimately.

**Comment by mmuziek** [comment]
1. answer : nope not possible the player is then not able to join the server if its in offline mode through the proxy
2. answer: its not an autorization proxy. bungeecord is to connect multiple servers to reduce the load over all servers i have set it to online mode and use a whitelist plugin to prevent offlinemode players to join so they have to join through the proxy but can then join all other server from the proxy instead of directly connecting to the servers.
3.answer: well bungeecord is a standard my setup is basic and strong i dont know how other servers do this but most of them i'm sure do not allow direct connections to their subservers so they also use the bungeecord proxy to let players connect and all subservers are also protected
4.i totally agree that it should be used legitimately thats why i come to you guys to find a solution for bungeecord users

**Comment by HappyHarm** [comment]
Was thinking but does getUUID() not get the uuid the server has registered, no matter or it is bungee or not? In that case getUUID should work for bungee and normal servers.

**Comment by TekkitCommando** [comment]
@JayWood, getPlayer() is deprecated because players can change their name causing trouble for donation plugins and ban systems. There is no plan to replace it; However getting the UUID fixes the change name problem that's why we still need it. Bungee is a pain and you can code bungee cord plugins. The only 2 plausible ways I think is to either you use your WordPress magic I have come to appreciate in order to authenticate the players. OR we create some sort of bungee cord part of WooCommerce that talks to the Bungeecord proxy.

**Comment by JayWood** [comment]
@TekkitCommando IF we can talk to the Bungee Proxy, then I'm all for it.  We absolutely need to use UUIDs for the exact reasons you just stated.

The problem on the WordPress side of things is we have no idea how Bungee is generating the 'fake' UUIDs, and WordPress contacts the Mojang API to get the REAL UUID. I believe most of this has to be done on the Java side of things, but I'm not entirely sure where to begin, since I don't have this type of setup.

One thing, if possible, would be to hook into the getUUID() method and override it somehow on the java side? I'm sure overriding the class, etc, isn't that hard, but I'd like to be 100% certain we should use this.

I wonder if there's a way of comparing the fake UUID and the Real UUID from the proxy? I kinda feel like this should be taken to the Bungeecord forum at this point.

**Comment by JayWood** [comment]
Purely off topic, and a rant of course, this makes me dislike BungeeCord - https://www.spigotmc.org/resources/fakeplayers-bungeecord.7887/

I think at this point I'm going to have to research what BungeeCord is, how it works, and what's possible with it, I'll report back in a day or so.

**Comment by mmuziek** [comment]
mabe its a bad idea. but cant it be possible to just validate the user online and then compaire the user on the server with the user from whats entered online
then you do not have the problem with uuids on servers because the player itself knows best what name he uses to play :)

**Comment by TekkitCommando** [comment]
@JayWood maybe.. @md_5 is the creator and he may see this or he may be on the forums a lot. I'm not sure if there is a bungee forums but there is a spigot forums and the lead dev of spigot is md_5 as well

**Comment by TekkitCommando** [comment]
@JayWood ok and yeah people use plugins to manipulate there player list and make fake players on tabs and stuff. I will let you think about it.

**Comment by TekkitCommando** [comment]
@mmuziek elaborate more, I'm not sure I understand what you mean xD

**Comment by mmuziek** [comment]
well you only want players that are real to buy stuff.
why not validate the user on wordpress and then check only the player name on the server.
that way there is NO way that it can break

**Comment by JayWood** [comment]
We need a two point check, getPlayer is deprecated and needs to be updated to getUUID, I'm taking this to the Spigot Forums and will post a link here relatively soon.

**Comment by TekkitCommando** [comment]
You forgot that it means resending donations is useless cuz they could change their name. We NEED UUID's xD

**Comment by TekkitCommando** [comment]
@mmuziek

**Comment by JayWood** [comment]
@TekkitCommando this looks promising - https://www.spigotmc.org/threads/get-mojang-account-uuid-from-proxiedplayer.15857/#post-177609

**Comment by TekkitCommando** [comment]
@JayWood ok

**Comment by TekkitCommando** [comment]
@JayWood hmm seems it may work correctly, we will find out more soon.

**Comment by JayWood** [comment]
@TekkitCommando Thread's up - https://www.spigotmc.org/threads/getting-real-uuid-string-from-a-proxy-setup.116974/

**Comment by TekkitCommando** [comment]
@JayWood Perfect, I would suggest renaming the thread "Getting real UUID string from a bungee setup?" if possible but doesn't really matter :P

**Comment by JayWood** [comment]
@TekkitCommando Looks like it's a config thing for both the proxy and sub-servers, at least according to DarkSeraphim - https://www.spigotmc.org/threads/getting-real-uuid-string-from-a-proxy-setup.116974/#post-1250879

Hoping he can give me some sort of official setup documentation link, but it's good to know that it's a config issue, nothing we need to change in the code, at least so far.

**Comment by JayWood** [comment]
@mmuziek looks like it's a config issue and something that needs to be configured on both Bungee and Spigot servers in order for the proper UUID to get to your sub-servers - see these links:

https://www.spigotmc.org/wiki/bungeecord-configuration-guide/ ( ip_forward must be true )
https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/

**Comment by TekkitCommando** [comment]
@JayWood Glad that was solved without the need for any code atm :D

**Comment by TekkitCommando** [comment]
@JayWood You know, All the time I spend programming different projects and the time I spend to learn new things, I think I would be pretty good as a remote java developer for a company if I don't make my own soon enough :P

**Comment by mmuziek** [comment]
sorry to give sad news but ip forwarding is set to true :(

**Comment by JayWood** [comment]
@mmuziek please read through all links, not just one. It's common to grab the first response and jump on it to try a fix without reading through all things. `hint: you also need to change a setting on your sub-servers' spigot.yml file`

Research is your best bet, everything we can find in regards to UUID's on Spigot and Bungee systems states that it can be done, granted my personal research is just two links. Unfortunately at this point, it would seem you are the only one having this issue ( granted this isn't a wide-spread plugin ).

I'm not saying that those links are right, hell I've never used Bungee, but I will not support offline mode servers at this point. The only thing I can do is take time to setup a full fledged Bungee setup, which considering the Monday launch date, is low priority.

**Comment by TekkitCommando** [comment]
Online = :+1:, Offline = :-1:

**Comment by JayWood** [comment]
Removing this from the Monday Milestone - Considering the updates that need to occur on the WordPress side to make this happen, we either push the 'official release' date, or push this.  And since `getPlayer()` works now, we'll just continue to use that for this release.

**Comment by JayWood** [comment]
Removing this entirely, super old ticket.
