### ISSUE TITLE
Question: Why use Java 7 instead of 8

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#37]
Why use Java 7 instead of 8? Java 8 has everything Java 7 has? any particular reason? :)

**Comment by HappyHarm** [comment]
Lot of servers are still on java 7

**Comment by TekkitCommando** [comment]
yes but I was wondering if there was a specific reason functionality wise

**Comment by TekkitCommando** [comment]
XD

**Comment by JayWood** [comment]
If I'm not mistaken, it's based on compilation.  ie. if you compile a jar against java8, regardless if it has everything java7 does, it will require the user to have java8 installed.

If we don't absolutely need functionality from Java8, why compile with it?

**Comment by TekkitCommando** [comment]
Java 8 helped server wise but yeah its more important that players can run it

**Comment by HappyHarm** [comment]
Saw you also got a repos for sponge, sponge itself is going to use java 8 so maybe you can switch to java 8 when people are going to use sponge.

**Comment by TekkitCommando** [comment]
@HappyHarm  Bukkit version can stay java 7  but yeah Sponge Version will require Java 8, that's gonna be a while tho :P

**Comment by JayWood** [comment]
Re-opening for discussion - I have no problem using Java8, right now that's what I have on my server, as well as my computer, and I agree, it does help with server performance.

I'm in the process of compiling the maven version of the project ( with some changes/todos/etc... ) and I have plugin issues on 1.7, hoping 1.8 can fix it, but idk yet.  If it compiles and runs on 8 I may just stick with that.

**Comment by TekkitCommando** [comment]
:+1:

**Comment by JayWood** [comment]
@TekkitCommando If i'm not mistaken, wasn't Java 8 a major security release?

**Comment by TekkitCommando** [comment]
@JayWood Yeah they also removed Perm gen space from servers

**Comment by TekkitCommando** [comment]
So makes it where you can run more intensely without having to specify how much perm gen memory

**Comment by JayWood** [comment]
I personally think we should stick with 1.8 with the security release ( and perm gen fix of course ). We should, however put a disclaimer in the plugin that it requires Java8.  Not just the Readme, but the plugin description as well, this will make sure all users know which java version they're supposed to use.

**Comment by TekkitCommando** [comment]
Agreed

**Comment by JayWood** [comment]
K, I've set the maven source/target to 1.8, closing.
