### ISSUE TITLE
i18n Updates - folder structure, and more stuff

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#43]
Currently we're writing the lang and config files manually.  I've since moved the default config.yml to resources so we can use `saveDefaultConfig()` instead of writing it ourselves, and `getConfig()` respectively.

We can use these directly within the main class since our main class already extends JavaPlugin, which is where these methods reside.  So I had an idea, looking at saveDefaultConfig() you'll see this:
```
public void saveDefaultConfig() {
    if(!this.configFile.exists()) {
        this.saveResource("config.yml", false);
    }
}
```
Simply put it looks in the java/main/resources directory of the build and basically copies it over into the dataFolder ( our plugin config folder ).  So I started looking into `saveResource()` and found that we only really need to modify the outDir result.

It's a big undertaking ( in my opiinion ) to essentially re-write the config methods of the main JavaPlugin.class file, so in the interest of time, I found this little gem: [Multi-Configuration Manager](https://github.com/corycaron5/Multiple-Configuration-Manager/blob/master/net/pandorramc/multiconfigmanager/ConfigManager.java)

We can cut it down to size, don't really need all that fancy stuff, but this seems to do what we're trying to achieve.

**Comment by JayWood** [comment]
I should add that we only need to make a 'saveDefaultLang' method if we use this library!

**Comment by JayWood** [comment]
Sweet, i18n LIVES!!!!
![878054b6760145c698c73662b36377c9](https://cloud.githubusercontent.com/assets/2303074/11764798/2ce6fa44-a10c-11e5-8271-4123ab1adc72.png)

**Comment by JayWood** [comment]
Thanks for the translations @TekkitCommando & @HappyHarm

**Comment by TekkitCommando** [comment]
@JayWood that's what I'm here for to maintain and make WooMinecraft better xD
