### ISSUE TITLE
maven merged into development & nightly

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#45]
I've merged all my changes from the maven branch into Dev and Nightly branches.  The plugin builds fine on Java 8 and runs fine as well.  There are more things to work on but it's 1:30 here and despite my enthusiasm I must sleep.

**Comment by JayWood** [comment]
I should add ( before I crash ) that there are things purposefully broken, one being the loading/saving of language files, and the other being the task runner, it just broadcasts a message instead of running check()

**Comment by TekkitCommando** [comment]
:+1:
