### ISSUE TITLE
Resources & External Links

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#46]
As best practice states, it's inadvisable to use external sites like Gyazo or Imgur to host images for the project.  The question is raised of "what if the site disappears".  To alleviate this, see these two commits:

a563067d857b1fec10e9c123adc8e0d0dedfe233
a563067d857b1fec10e9c123adc8e0d0dedfe233 ( Fixed my oops :smile:  )

**Comment by JayWood** [comment]
Of course by using the resources folder this means that the .png gets packages with the plugin, but it's just one little png, so no worries there.  We could undoubtedly move it elsewhere, but I figured /resources/ was a good place to store a logo.

**Comment by JayWood** [comment]
@TekkitCommando close this after you've seen it

**Comment by TekkitCommando** [comment]
:+1:
