### ISSUE TITLE
Suggestion: Update WooMinecraft page on personal site

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#47]
@JayWood I suggest updating the WooMinecraft page on your personal page to say it supports CraftBukkit/Spigot 1.8.x and so on :P

**Comment by JayWood** [comment]
Noted - really lazy to login to my site, but I'll definitely get on that... eventually :smile:

**Comment by TekkitCommando** [comment]
Lol cool xD
