### ISSUE TITLE
Some questions for wiki

### ISSUE THREAD

**Issue by HappyHarm** [WooMinecraft/WooMinecraft#49]
Hi there,

Thought because I can't really code, I could help with updating the wiki a bit. Only got 2 questions about it.

1. Could I delete the old homepage from the wiki? ("WooMinecraft Wiki")
2. Where are the downloads for the wordpress side of WooMinecraft now? Only saw at the latest release(s) a download for the jar and it's sourcecode. Is there now a new repos or something for the wordpress thing?

**Comment by TekkitCommando** [comment]
1. Yes

2. Yes its at this link https://github.com/WooMinecraft/woominecraft-wp
just download the repo as a zip :)

**Comment by HappyHarm** [comment]
Ah maybe remove the wordpress folder in this repos then. It's a bit confusing.

**Comment by TekkitCommando** [comment]
that's only in master I think, when we have everything stable we will update master :)

**Comment by TekkitCommando** [comment]
@HappyHarm I have invited you to a documenters team on the organization just go to http://www.github.com/WooMinecraft and click view invitation

**Comment by HappyHarm** [comment]
Thanks, joined it :)

**Comment by TekkitCommando** [comment]
:+1:

**Comment by TekkitCommando** [comment]
@HappyHarm Close this when you are done with the jist of the wiki

**Comment by HappyHarm** [comment]
jist? Don't know that word :)

**Comment by HappyHarm** [comment]
Nvm searched it

**Comment by TekkitCommando** [comment]
xD

**Comment by HappyHarm** [comment]
Added the woocommerce plugin installation tutorial, I even used pictures :P Will explain tomorrow how you can add items etc.

**Comment by TekkitCommando** [comment]
@HappyHarm Thanks :)

**Comment by HappyHarm** [comment]
Btw shall I move some of the md files like contributor guidelines etc to the wiki? That cleans up the repos a bit.

**Comment by TekkitCommando** [comment]
Nah we need them in the repos cuz at some points github will auto suggest that you read them when doing specific things :)

**Comment by HappyHarm** [comment]
Ok, I have added a package tutorial as well and updated the download links. I think there is nothing more to do in the wiki for now. When there are new features I'll update the wiki :)
