### ISSUE TITLE
Just letting you know 

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#54]
@JayWood Today's my birthday, I turned 18 :) and so I am hanging out with my family this weekend and won't be able to work on WooMinecraft till Sunday :+1:

**Comment by JayWood** [comment]
@TekkitCommando Thanks for the info, but don't EVER think this plugin is an obligation, nor is it a job! Live your life dude!!!

**Comment by TekkitCommando** [comment]
Np :) and ok :P

**Comment by HappyHarm** [comment]
Congratulations with your birthday :)

**Comment by TekkitCommando** [comment]
@HappyHarm thanks
