### ISSUE TITLE
Plugin Organization Question

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#56]
@JayWood Was there a specific reason why the commands folder was removed and all the classes are in the main directory, in my experience plugins were always organized, command classes in commands folder, update checker and stuff in a util folder or something and metrics in a metrics folder if applicable. Just wondering, if there was no reason I was gonna spend time organizing the classes a bit

**Comment by JayWood** [comment]
honestly zero reason, i think it was in an attempt to debug something, but I never put it back.  Feel free to organize away.

**Comment by JayWood** [comment]
@TekkitCommando on a side-note, if there are any official documentation on Minecraft Plugin Design Patterns I'd love to have a read, I'm all about standards, but my newbie appeal usually steers me into the 'get it working' design pattern.

**Comment by TekkitCommando** [comment]
@JayWood I used to be major into bukkit/CraftBukkit development I will see if I can find the old document I used to follow when I first started working on PromitionEssentials.
