### ISSUE TITLE
broken plugin

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/WooMinecraft#59]
hi there. i downloaded all versions and tested them all out.
the wordpress part seems to be working but the plugin is not
it spamms a protocol error and from what i read its that it does not read the config.
it also sais that the key is already generated even when there is an empty config file in the folder.
if i put everything in manually it spams with NULL?woo-minecraft.....?key=NULL
so it doesnt read the config. i am using spigot 1.8.8 at the moment
and wanna know if this is already fixed or still being fixed.
i am no java dev myself so i like this awesome project very much.!

**Comment by TekkitCommando** [comment]
atm our changes to the config system aren't compiled, and the check for donations to the WordPress side was disabled by @JayWood I forgot for what reason though.

**Comment by mmuziek** [comment]
can you give me an eta for when its working?

**Comment by TekkitCommando** [comment]
We plan to have the system working asap though. I have java courses again but after I am done I am coming back to this to fix EVERYTHING xD

**Comment by TekkitCommando** [comment]
@mmuziek I cant give a specific date but soon.

**Comment by HappyHarm** [comment]
Thought there were already stable releases available weren't they?

**Comment by mmuziek** [comment]
yes there are but they are not working

**Comment by TekkitCommando** [comment]
I think at one point I thought I fixed it but there was a database problems, we started rewriting things to make them work better and we have a few things to do. The config problem is fixed in the latest source code push on dev-nightly branch but donation checks were disabled by @JayWood and like I said I forgot why. When he sees this he will probably say why.

**Comment by HappyHarm** [comment]
I thought the key was nothing more then some random generated characters that had to match for the wordpress side and the server side. So you could try to just put in some random characters.

**Comment by TekkitCommando** [comment]
@HappyHarm yes, and we fixed it in the latest code but the last compiled version that @mmuziek has, I tried something with the Config system and it always reset the key and the code saw it as null. However it is fixed and I could recompile a new pre version of WooMinecraft but donation checks were still disabled by @JayWood and we have to wait for him to remind me why :P

**Comment by mmuziek** [comment]
can we manually do a check or is that also disabled in that compile?

**Comment by HappyHarm** [comment]
@TekkitCommando The donations request were handled by the server side wasn't it? For now @mmuziek can use the latest compiled release and just fill in his own key. The wordpress checks weren't removed at that release were they?

@mmuziek try to fill in a random 32 characters key in the config.yml and let it match with the key you fill in in the wordpress thing.

**Comment by TekkitCommando** [comment]
@HappyHarm but I will be getting back to this after I refresh my java knowledge with the courses I am taking. and @mmuziek manual checks and auto checks both pointed to the same function (coding method), one was just auto and the command was manual.

**Comment by mmuziek** [comment]
@HappyHarm i tried that but it generated huge errors when it checks for the packages

**Comment by TekkitCommando** [comment]
@HappyHarm It was saved by the server, yes, but the plugin still has to make a check to give the rewards for the donation. and his version was the one with the null error and config resets.

**Comment by HappyHarm** [comment]
@TekkitCommando Ah, but the stable release should work?

**Comment by mmuziek** [comment]
@tekkitcommando cant you enable the manual check and compile it for us?

**Comment by TekkitCommando** [comment]
@HappyHarm It shouldn't take long for Jay's email to get spammed and he checks this issue and reminds me why checks were disabled xD

**Comment by TekkitCommando** [comment]
@mmuziek @JayWood disabled it so I figure it doesn't work or he was right in the middle of something and so there would probly be errors.

**Comment by TekkitCommando** [comment]
@mmuziek If @JayWood doesn't write back to this issue soon I will look at the donation check method and compile and see if it works.

**Comment by TekkitCommando** [comment]
@mmuziek Thank you for taking an interest in this project! We will try to fix your problem as quickly as possible :)

**Comment by TekkitCommando** [comment]
Or maybe I'm crazy... Idk anyways I am sure JayWood will comment back soon

**Comment by JayWood** [comment]
There's no reason for the check to be disabled in the java side on dev-nightly, that is if you're referring to issue #57 @TekkitCommando 

Feel free to un-comment and recompile, or fix whatever you see necessary to get that working.  On the flip side @mmuziek I'm aiming to have a full stable release, both Java, and WordPress by next Monday.

**Comment by JayWood** [comment]
@TekkitCommando nvm :) it was just a click away.

**Comment by JayWood** [comment]
@mmuziek You'll need to compile from the dev-nightly branch, not master for the plugin to work with the Key issue.  I'm pretty sure @TekkitCommando and I have already handled that, but it's been a month since I touched the code ( roughly ) - so don't hold me to that.

Either way, by Jan. 25th there will be a complete stable release of both WordPress and Java plugins.

**Comment by mmuziek** [comment]
@jaywood i have no knowlage of compiling can you teach me how or make a small compile of the dev build?

**Comment by TekkitCommando** [comment]
@JayWood Awesome! Like I said I will be done with my programming courses soon and will be helping with this once more.

**Comment by HappyHarm** [comment]
@mmuziek gimme a moment will compile it for you.

**Comment by TekkitCommando** [comment]
@mmuziek I can compile the dev-nightly branch after school today :)

**Comment by TekkitCommando** [comment]
@HappyHarm beat me xD

**Comment by HappyHarm** [comment]
@mmuziek http://www.filedropper.com/woominecraft-104-snapshot

**Comment by mmuziek** [comment]
thanks i will check it out right away!

**Comment by HappyHarm** [comment]
Seeing a small (where I think it is an issue) now. When the config for the first time generates there is no key. When you use /woo register you key a key but the config only stores the key and the rest of the config is wiped http://prntscr.com/9s20s2.

**Comment by mmuziek** [comment]
same issue but i fixed it manually by first editing the config and pasting in the last key it generated

also it seems to not work
[13:34:11] [Server thread/ERROR]: [WooMinecraft] Connection refused
[13:34:11] [Server thread/WARN]: [WooMinecraft] Cannot open Data Output Stream!
whats this error?

**Comment by TekkitCommando** [comment]
I have always compiled in Java 8 but I doubt that matters. Hmm that issue has never happened before but I will run some checks when I get home. @HappyHarm feel free to submit an issue on it.

**Comment by HappyHarm** [comment]
@TekkitCommando @mmuziek sees to have the same issue :P Will open a issue in some minutes. 

@mmuziek Did you set the same key in the wordpress thing as well as in the server thing?

**Comment by TekkitCommando** [comment]
@mmuziek the connection to the website set in the config was refused.

**Comment by mmuziek** [comment]
ok how do i fix that my website uses https:// for instance?

**Comment by mmuziek** [comment]
lang: en
update_interval: 1500
url: https://bitcubes.eu
key: -- < key hidden

**Comment by HappyHarm** [comment]
@mmuziek try to use http? Maybe that will fix it

**Comment by TekkitCommando** [comment]
Also make sure your key is already in the WooMinecraft key thing on your WP Admin Panel just in case.

**Comment by mmuziek** [comment]
ok now i get [13:43:18] [Server thread/ERROR]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

**Comment by TekkitCommando** [comment]
Hmmm JSON Classes were a Jay Wood thing xD @JayWood could you please tell him what's wrong.

**Comment by mmuziek** [comment]
i think i know my wordpress is on POSTNAME permalink setting not the default i cant get it to change

**Comment by HappyHarm** [comment]
@mmuziek I think you can better wait until JayWood gives you the answer. I think he can trace this errror back as best of us.

**Comment by mmuziek** [comment]
@HappyHarm well i tried to test it out but i cannot change the permalink setting in my wordpress it goes back to the last setting so i think something is wrong with my htaccess file or something so i will wait for @jaywood to reply and see what his solution is

**Comment by mmuziek** [comment]
@jaywood any news on this matter? or should i make a new issue for it?

**Comment by TekkitCommando** [comment]
@mmuziek make a new issue please so i can label and assign it accordingly

**Comment by JayWood** [comment]
@mmuziek the error is due to data that's not being returned properly.  I'm not entirely sure exactly what that data is, not without being ON your server.

I would consider the dev-nightly build unstable, at best, as well as the WordPress build - everything should be fixed up by Monday.

**Comment by JayWood** [comment]
Too much going on, closing this thread.  Please open a more 'targeted' thread if the problem persists after Monday's launch.
