### ISSUE TITLE
subscription items

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/WooMinecraft#62]
Hi there.
my suggestion is subscription items. or variable time stamps

soo  a player chooses 30 days from a variable option or choose a month or buys a month item.
they currently get their rank ingame but its never removed automaticly

are there plans to implent this or not? or are there other ways to do this free or for a small fee?

this is my suggestion thanks for reading :D

**Comment by TekkitCommando** [comment]
So you want there to be an option for recurring payments on donations?

**Comment by mmuziek** [comment]
something like that or a way to do that because my ranks are for 1 month or 1 year not permanent

**Comment by TekkitCommando** [comment]
Thats a WooCommerce thing really and if were to look at it as a WooMinecraft feature it would be a WooMinecraft-WP thing. Please submit your suggestion at https://github.com/WooMinecraft/WooMinecraft-WP/issues/new but I am thinking that's a WooCommerce thing. Maybe not, this is where @JayWood is handy, I'm Java and he's PHP/WordPress xD

**Comment by JayWood** [comment]
Definitely a WordPress thing.  Has nothing to do with Java. There is already a plugin available for WooCommerce - https://www.woothemes.com/products/woocommerce-subscriptions/ price tag on it is around $200.

Personally, I do not own that plugin, and to provide testing/integration for that plugin, well, I need to own it. I will say the WordPress side of things for WooMinecraft ONLY inserts commands into the database when an order is marked as `completed`.

It 'may' be compatible out of the box, but again, I don't own that plugin, nor do I see myself paying $200 for it JUST to integrate it.

A 'free' alternative would be PEX ( PermissionsEx ) - it has TIMED commands like so `pex user <user> timed add <permission> <lifetime in seconds> [world]`

Here's the PeX wiki - https://github.com/PEXPlugins/PermissionsEx/wiki/Commands
