### ISSUE TITLE
Claim products sign / command (suggestion)

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/WooMinecraft#63]
Hi.
i was thinking. if this plugin calls for the products and directly activates the commands then its possible the player overflows his inventory and then loses some items.

mabe its an idea to make a toggleable setting to only allow manual receiving of order.
so when someone buys something its not automaticly given. it waits until that person clicks on  a sign or enters a command then executes the commands. this will prevent lots of problems later on when giving items or item packs

that would be awesome!

**Comment by JayWood** [comment]
There's code already in place to ensure we don't try to give items to a user if they don't have adequate inventory space - https://github.com/WooMinecraft/WooMinecraft/blob/dev-nightly/src/main/java/com/plugish/woominecraft/WooMinecraft.java#L179-L187

**Comment by JayWood** [comment]
@mmuziek Additionally we can expand on that check ( I know bukkit uses `/i` instead of give ) or, we can force the command on the WordPress side with like a checkbox or something.

There is, however, plans for this already, just no official task.

**Comment by mmuziek** [comment]
em one problem.
if you have essentials installed it uses essentials give command which doesnt check inventory space

**Comment by JayWood** [comment]
Simple solution, when making your commands, use `/give <player> item:meta` - The code checks slots if the command saved in the WordPress database starts with `/give`.

**Comment by mmuziek** [comment]
ok nice do i have to use / in the command and how do i specify amounts?

**Comment by JayWood** [comment]
Just append the amount at the end of the command, and no, do not include the `/` character.

**Comment by HappyHarm** [comment]
Uh essentials does override give right?

**Comment by JayWood** [comment]
Putting this on the back-burner for now.
