### ISSUE TITLE
status not found

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/WooMinecraft#64]
hi there.
i was trying out the latest dev build and tested it against the plugin i have
and i get
[21:50:55] [Server thread/INFO]: mmuziek issued server command: /woo check
[21:50:56] [Server thread/WARN]: [WooMinecraft] JSONObject["status"] not found.
its possible i have my plugin behind on commits but when i check it myself:
i get
{"success":false,"data":{"msg":"No results for the following players: \"mmuziek\"","status":"empty","code":6}}
the strange thing is that i do have commands waiting and i do have the name mmuziek but still it doesnt see it i think it has something to do with the \ inside the strings

**Comment by JayWood** [comment]
@mmuziek That has nothing to do with the backslash, the slash is there to escape the double quotes - I'll have a look and report back.

**Comment by mmuziek** [comment]
i tested the last version of the plugin and it still occuers
[11:54:30] [Server thread/WARN]: [WooMinecraft] JSONObject["status"] not found.

**Comment by TekkitCommando** [comment]
I will probably try to look into that a little today.

**Comment by JayWood** [comment]
@mmuziek Fixed in latest pre release https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.0.4pre-1
