### ISSUE TITLE
Launch Delays

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#65]
Today has just been crazy for me - I won't be able to squash all the required bugs and get testing done  to `officially release` this today.

I'm hoping sometime this week at least, but for now, it's tea and bed for me!

@TekkitCommando - If there's anything you can do on the java side I'd be grateful, if not, no worries, I'll get to it as soon as I can.

**Comment by TekkitCommando** [comment]
I will try to find the time today to clone the project on my old laptop

**Comment by mmuziek** [comment]
i'm so sad now :(
well anyways if there are changes to the plugin can you please compile it so i can test it?
i sure wanna keep testing until it works!

**Comment by TekkitCommando** [comment]
I will be looking at the Java side of things today after school and see what needs to be fixed @mmuziek I will build a jar sometime today.

**Comment by HappyHarm** [comment]
Hope you'll get well @JayWood!

**Comment by mmuziek** [comment]
hi there i see everyone is busy.
can i do anything beside java coding because i still dont know how to do java and how to compile anything.

anyways i'm ready to test stuff try stuff or thinking of new ideas and methods

**Comment by TekkitCommando** [comment]
@mmuziek I am busy with school and I'm doing my PHP and Java courses so that takes up my time at home cuz I learn those online, when I'm done like I said I will get back to this. I forgot to compile the WooMinecraft changes for you so I will do that rn, but major changes will probably come when I'm done with my Java and PHP courses.

**Comment by TekkitCommando** [comment]
And yes keep thinking up ideas and help we really appreciate it

**Comment by TekkitCommando** [comment]
If you know PHP and want to help out with coding fork the WooMinecraft-WP repo and make your changes then send a PR for us to test :(

**Comment by TekkitCommando** [comment]
:)*

**Comment by TekkitCommando** [comment]
@mmuziek Added a new jar.

**Comment by mmuziek** [comment]
any news on updates or fixes for one of the projects.
as my website is now broken i had to remove the plugin from my website because of the problems.

well anyways i hope to receive  a reply with the answer soon as my deadline approaches

**Comment by TekkitCommando** [comment]
Still am not done with the programming classes, so I still have school to worry about, and I got a funeral to go to this weekend so I won't have the time to do anything rn.

**Comment by JayWood** [comment]
@mmuziek How did the WordPress plugin break your site in such a way that it required you to remove it? The only thing it does is add a field to checkout, and adds 'command fields' to products in the admin.

**Comment by mmuziek** [comment]
well simple as soon as someone buys something or registers.
it shows a white page with the json output on it which breaks the signup and checkout process

**Comment by JayWood** [comment]
@mmuziek Hehe, well that's the trouble with nightly dev builds :smiley_cat: Thanks for the report tho!
