### ISSUE TITLE
Names not being sent to WordPress server

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#66]
Looking at `Connection.processNames` and debugging the output in WordPress, we're not getting player names, this is probably due to my mis-understanding of how the Connection class should be written.

Irregardless of my ignorance, if we can't send names, we can't send UUIDs ( later ) so this needs fixed. @TekkitCommando if you get time would you take a look? I believe once we have this fixed we should be good for a stable release.

Either way if you can't I'll get around to it sometime this week.

**Comment by TekkitCommando** [comment]
Yeah I will have a look after school today

**Comment by JayWood** [comment]
@TekkitCommando fixed it - note to self, don't pass around an object and NOT unset it when finished.

**Comment by TekkitCommando** [comment]
Lol ok, sorry, more personal things came up. I am trying to get everything figured out AND finish my Java and Python classes. Like I said, once I am finished with them I will be back to working on this all day like before :P
