### ISSUE TITLE
Release Naming Conventions

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#67]
@TekkitCommando In doing a release today, I seen that Github orders releases alphabetically?  Or maybe by commit hash? idk... 

What I'm wondering is if we can standardize, in some way, the release titles.  For example:
`Pre <version> <stable/unstable> Release` - For pre releases
`<version> Release` - For official releases

To be honest, I usually don't do 'releases' I merely tag a version and push the tag, but drafting a release seems to be the best idea since we can provide the jar and zip files etc... So I was wondering what's your thoughts - or if you'd like to follow some sort of standard from the Spigot/Bukkit community?

**Comment by mmuziek** [comment]
well its not stable as i get the json error again :*

**Comment by TekkitCommando** [comment]
I have a great idea for this, I will type out the idea tonight once I'm in my hotel.

**Comment by TekkitCommando** [comment]
@mmuziek it may be your wordpress site? I will test it on my Wordpress site tomorrow

**Comment by JayWood** [comment]
@mmuziek did you download the latest stable pre-release for WordPress as well?

**Comment by mmuziek** [comment]
yesi did

**Comment by JayWood** [comment]
@mmuziek Please open a new ticket and paste the debug log if you wouldn't mind.

**Comment by JayWood** [comment]
Also @mmuziek make sure you clean out the config for the plugin, just in case.

**Comment by mmuziek** [comment]
i have let it regenerate the config file but it seems that it also has the config issue too
it wipes the config but the key so i had to reset the whole plugin again and enter the earlyer made key into the config

**Comment by TekkitCommando** [comment]
Why enter the earlier key? Why not let it generate a new UUID and update the key in WP dashboard

**Comment by JayWood** [comment]
This is off topic again, please keep relevant conversations in the relevant threads, for the sake of history :smile: - closing this.  @TekkitCommando let me know when you have that up so I can take a look.

**Comment by TekkitCommando** [comment]
@JayWood Alright

**Comment by TekkitCommando** [comment]
@JayWood I think we can just go with your idea, that should work fine :) but instead of tagging with stable/unstable maybe tag with Alpha, Beta, or Mature like Bukkit does. Alpha meaning may be unstable, Beta meaning most likely stable but there could be a bug here and there, and Mature meaning you probably won't find any bugs and we recommend using this version. What you think?
