### ISSUE TITLE
json broken again

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/WooMinecraft#68]
he he the bug is not fixed yet as for prerelease stable
06.02 19:37:44 [Server] ERROR [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
it seems we are back where we left off :(

**Comment by TekkitCommando** [comment]
was this a thing with you Jay?

**Comment by TekkitCommando** [comment]
Is it possible it is only his site

**Comment by mmuziek** [comment]
you may take a look its bitcubes.eu
if you want i can give you the shop key (i can reset the key later on for safety)

**Comment by JayWood** [comment]
@TekkitCommando I asked him to open a new thread so we didn't get off topic again.

@mmuziek Please provide me your security key ( from WordPress, as well as your settings from the plugin in MineCraft ) - I tested this thoroughly and was able to get donations delivered, which leads me to believe it's your wordpress server.

Give me 24 hours to test a few things please, I'm out right now and won't be home for at least a few more.

**Comment by TekkitCommando** [comment]
@JayWood Ok

**Comment by mmuziek** [comment]
`# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: en

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: https://bitcubes.eu

# This must match the WordPress key in your admin panel for WooMinecraft
# For security purposes, you MUST NOT leave this empty.
key: 0e94d01b4b53454b9314f30c2c4ccbb8`

in my wordpress its : 
0e94d01b4b53454b9314f30c2c4ccbb8

**Comment by JayWood** [comment]
@mmuziek copy paste your full config, or take screenshots, that formatting is horrendous :)

**Comment by mmuziek** [comment]
http://pastebin.com/raw/arS14UUq

**Comment by JayWood** [comment]
@mmuziek - I did a query against your site with the key provided, and got back a json structured response, like I should have. Note the URLs and responses.
![](https://i.gyazo.com/9594196bb23f0cc83a1f8660c53584e0.png)

So, that means the only issue would be the jar file - Make sure you have the stable jar file from here: https://github.com/WooMinecraft/WooMinecraft/releases/tag/1.0.4pre-1

Once installed you must restart the server. You can't just `/reload` - let me know if that helps.

**Comment by TekkitCommando** [comment]
It is recommended that like once a week completely stop and start your server

**Comment by mmuziek** [comment]
em i always restart my server for plugin updates at least once a day! i never reload as this crashes my server network.
i'm testing it once again :+1:

**Comment by mmuziek** [comment]
well it seems to work now after 5 restarts .
it seems it didnt pick the config changes i made. and resets the config so i stopped the server after 4 tries and then edited the config then startup the server again and now it works :dart:

**Comment by JayWood** [comment]
Sounds like something on the jar side of things was cached, but glad it's working for you.
