### ISSUE TITLE
WooMinecraft Available on Plugin Repositories

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#69]
@JayWood now that there is a stable release mind if I get WooMinecraft available on Spigot and BukkitDev and maybe you could upload the WP version to the Wordpress plugin repository, idk how the WP plugin repository works so I will leave it to the expert :P

**Comment by mmuziek** [comment]
here ya go its not that hard
https://nl.wordpress.org/plugins/about/
and for spigot just login and submit resource :)

**Comment by TekkitCommando** [comment]
I know how on Spigot/Bukkit I have plugins already available :P I just didn't now about the WP Plugin Repository xD Thank though :) I may still leave the WP side of things to @JayWood

**Comment by JayWood** [comment]
@TekkitCommando I'll submit it before monday to WP.org, but I have to make a proper Readme.txt file beforehand, which shouldn't be an issue.  I already have 2 plugins on .org repo so I know how it goes

As for submitting it to Spigot and others, I don't see why not..

**Comment by TekkitCommando** [comment]
Alright cool

**Comment by TekkitCommando** [comment]
@JayWood made the pages for both Spigot and Bukkit.

**Comment by JayWood** [comment]
@TekkitCommando Link? Also, submitted to WordPress.org

Additionally, both WP and Java code is officially released on master!

**Comment by TekkitCommando** [comment]
@JayWood https://www.spigotmc.org/resources/woominecraft.18126/ and https://dev.bukkit.org/Bukkit-plugins/WooMinecraft 

I need to add zip folders with a readme and the WP plugin and jar for convenience as the download on those pages, I will do that in about an hour when I'm on my laptop

**Comment by JayWood** [comment]
Cool beans, thanks man.

**Comment by TekkitCommando** [comment]
Np

**Comment by JayWood** [comment]
Blog post up, creds for @TekkitCommando and @mmuziek in there as well :) http://www.plugish.com/2016/02/woominecraft-self-hosted-donation-system/

**Comment by HappyHarm** [comment]
@TekkitCommando It looks like the spigot page didn't got copied really well. Think they are using an another styling system then bukkit.

**Comment by mmuziek** [comment]
@jaywood thanks man for the credits :)
i keep on testing for you  :)

**Comment by TekkitCommando** [comment]
@HappyHarm Yeah I was on my phone and waking down a sidewalk and didn't spend to much time lol

**Comment by JayWood** [comment]
@TekkitCommando - Repo approved on .org https://plugins.svn.wordpress.org/woominecraft/ will upload it hopefully sometime in the next few days.

**Comment by JayWood** [comment]
@TekkitCommando We're now on .org https://wordpress.org/plugins/woominecraft/ - This means that I don't have to worry about people complaining 'my version is out of date' when they only need to click update in the WordPress admin now.

**Comment by TekkitCommando** [comment]
awesome!
