### ISSUE TITLE
Updating the wiki

### ISSUE THREAD

**Issue by HappyHarm** [WooMinecraft/WooMinecraft#70]
Hi there,

Saw everything has been updated and the project has been put on SpigotMC now so I thought it is time to update the wiki :P So my question was is there a changelog available with things that have changed so I can review the wiki?

**Comment by TekkitCommando** [comment]
I am updating the changelog on my website after I upload the zips to the Bukkit and Spigot pages, you can read off that.

**Comment by HappyHarm** [comment]
A question: where should people download the lang files? I see that there is a folder with lang files in the /resources/lang and a repos for the lang files. Which one is the one that I should link to in the wiki?

**Comment by TekkitCommando** [comment]
The repo with the lang files is for convenience so if you just need the lang files you don't need to download all the code as well. So I guess the repo

**Comment by HappyHarm** [comment]
Then I guessed it right :P Just updated the configuration wiki page btw :)

**Comment by TekkitCommando** [comment]
@HappyHarm No, most of everything was bug fixes with 1.0.4 but you may need to update the bukkit setup so the config is not nested anymore as soon as I figure out why java is not resetting the data with a new jar.

**Comment by HappyHarm** [comment]
@TekkitCommando I guess I did that already but don't really get what you mean. Could you check https://github.com/WooMinecraft/WooMinecraft/wiki/Step-1:-Server-Plugin-Installation and say or it is good so far?

**Comment by TekkitCommando** [comment]
@HappyHarm Yes that's good :)

**Comment by JayWood** [comment]
@HappyHarm Just to chime in, you may want to put ( in the wiki ) a list of available language parameters for the Lang config option and what language they represent - you can see the files here: https://github.com/WooMinecraft/WooMinecraft/tree/master/src/main/resources/lang

The `en` lang selection would correspond to the `en.yml` file in the directory.

**Comment by HappyHarm** [comment]
@JayWood ok but do people need to download them then? Or for example if I want the Dutch language file I just have to set it to nl and it will get the language file automatically?

**Comment by JayWood** [comment]
@HappyHarm No they don't have to download it, setting the parameter in the config will automatically pull it from the jar file and put it in the config folder, then load it.

**Comment by HappyHarm** [comment]
@JayWood Thx, was already wondering why they were in the resources folder :smile:

**Comment by HappyHarm** [comment]
@JayWood Updated the language part. Think it's correct now.

Another question, I saw on this picture on the wp repos that you used some way to manage timed commands or something and that you are using variable product in stead of simple product.
https://raw.githubusercontent.com/WooMinecraft/woominecraft-wp/dev/screenshot-2.png
Is there a specific reason for? I did something else on the wiki xD

Btw, when you click on "Visit plugin website" in the plugin overview from wordrpess you get to this website (http://www.plugish.com/plugins/minecraft_woo) that leads to nothing.

**Comment by JayWood** [comment]
@HappyHarm re: timed commands

There's an old issue about that, to do timed commands you'd have to use something like PEX or other systems.  I just did that for an example.

For the plugin site issue, I'll have to update the page.

**Comment by JayWood** [comment]
@HappyHarm for variable products check this out - they're really handy: https://docs.woothemes.com/document/variable-product/

**Comment by HappyHarm** [comment]
@JayWood Will read it. But is it recommend for minecraft packages?

**Comment by JayWood** [comment]
Yes, WooMinecraft supports product variations, or 'packages' as it can be called.  All you have to do is make sure your 'variations commands' are indeed in the variations, not in the general commands section.

You can, however put commands in the general commands AND a variation.  If a command is in the general commands, it runs before the variation commands.

Your example works perfect, say you're selling a Blue T-Shirt, but comes in S, M, L, and XL.  You would create the product 'Blue T-Shirt' , then add the sizes, each as it's own attribute/variation. Then, once you create the variation, you can add specific commands to that variation, to be ran ( on top of the general commands ) when a user purchases say the S size shirt.

**Comment by HappyHarm** [comment]
@JayWood Ah now I get whay you ment with that example picture. Will think about writing something about this in the wiki.

**Comment by JayWood** [comment]
@HappyHarm please close this when complete.

**Comment by HappyHarm** [comment]
Whoops forgot that this was still open. Don't have any questions anymore so I'll close it.
