### ISSUE TITLE
Checking for donations generates an error.

### ISSUE THREAD

**Issue by Pandoroxus** [WooMinecraft/WooMinecraft#71]
Whenever I run /woo check an error appears in the console.
[Error Here](http://pastebin.com/rW2uDTE8)
I'm running 1.0.0 of the WordPress build and 1.0.4 of the Server Jar.
Any help would be appreciated.

**Comment by JayWood** [comment]
:whale2: - Fail whale.... ugh, well thanks for the ticket, looking into this immediately :(

**Comment by JayWood** [comment]
@Pandoroxus I cannot replicate this, but I've added the Accept-Charset header in the last commit hoping that will fix it, in accordance with this http://www.checkupdown.com/status/E406.html

Should have a jar file shortly

**Comment by TekkitCommando** [comment]
@JayWood If there any new commits can we start doing sub build versions (for example: 1.0.4.1) so I can track the changes and update the plugin files accordingly on Bukkit/Spigot xD

**Comment by JayWood** [comment]
Sub-builds? I'm not used to doing that but I can, how do you want me to label this fix?

**Comment by JayWood** [comment]
@Pandoroxus - Give this file a go, until @TekkitCommando gets back to me.

[WooMinecraft-1.0.5-SNAPSHOT.zip](https://github.com/WooMinecraft/WooMinecraft/files/120925/WooMinecraft-1.0.5-SNAPSHOT.zip)

**Comment by Pandoroxus** [comment]
@JayWood Thanks, I'll test it and report back ASAP.

**Comment by JayWood** [comment]
Also, can you tell me if your web-server has any special configurations to disallow specific headers, such as modSecurity, or CSF? ( if you have any idea what those are )

**Comment by TekkitCommando** [comment]
@JayWood Maybe just WooMinecraft <version> Fix #<number> so like WooMinecraft 1.0.4 Fix #1 then in the description describe the fixes. Just my opinion, makes it more organized :D

**Comment by JayWood** [comment]
@Pandoroxus Additionally, install the latest version of the WordPress plugin here https://github.com/WooMinecraft/woominecraft-wp/releases/tag/1.0.1

Just had to release a hotfix for it, so make sure you get it on your server.

**Comment by JayWood** [comment]
@TekkitCommando How about RC? I see it in plugins all the time, like Bukkit_1.7.10-RC1

**Comment by TekkitCommando** [comment]
Yeah Release 1 like CraftBukkit, works for me :)

**Comment by JayWood** [comment]
@TekkitCommando Cool, I know RC stands for release candidate, so makes sense. I'll wait for @Pandoroxus to report back though, if that fixes it I'll get it up there, if not I need to look into the HTTP 406 error more, and that may take awhile.

**Comment by TekkitCommando** [comment]
@JayWood Alrighty :)

**Comment by Pandoroxus** [comment]
@JayWood I tried the 1.0.5 and it didn't seem to make any difference. I went into my config and added www. to the start of the URL and the error from before went away (I think it's because of our DNS settings, our server and website share the URL and I was worried the request was going to the wrong place (even though it shouldn't)). Now I'm not getting any errors but the donations aren't coming through to the server.

**Comment by TekkitCommando** [comment]
@Pandoroxus Can you paste your config on pastie.org and send me the link? @JayWood do donations still need to be marked as completed before the donations are sent?

**Comment by JayWood** [comment]
@TekkitCommando yes, donations must be marked as completed before they're sent to the server.

**Comment by Pandoroxus** [comment]
@TekkitCommando [Here](http://pastie.org/private/1bnkr6vk2go5n5p5mkjn1q)
Also, on a semi-related note when I type the URL into my browser (putting &names=Pandoroxus at the end because it ends up in the same superglobal) it returns the expected result, so whatever's derping must be to do with the (minecraft) server.

**Comment by JayWood** [comment]
@Pandoroxus can you post your log from when you run `/woo check` as well

**Comment by TekkitCommando** [comment]
@Pandoroxus have you set the donation as completed?

**Comment by JayWood** [comment]
@TekkitCommando looks like he does - http://creationbaymc.com/?woo_minecraft=check&key=54add0280f7145fab88af9c5cc345da0&names=Pandoroxus

Without the order being completed, that data wouldn't show.

**Comment by TekkitCommando** [comment]
@JayWood Ok

**Comment by Pandoroxus** [comment]
@JayWood @TekkitCommando That's exactly what I do. Running /woo check just shows 07.02 15:02:27 "[Server] INFO No donations for online users." in the console. (I'm online and not vanished on the server)

**Comment by JayWood** [comment]
@Pandoroxus paste your woominecraft config if you wouldn't mind.

**Comment by Pandoroxus** [comment]
@JayWood The config is the "here" in my last comment.

**Comment by JayWood** [comment]
OH, sorry didn't see that :)

**Comment by JayWood** [comment]
The only thing I can think of is it's how your server is setup on the DNS side of things.  Having www vs. non www I mean.

For instance, this link works: http://creationbaymc.com/?woo_minecraft=check&key=54add0280f7145fab88af9c5cc345da0&names=Pandoroxus

But, so does this one: http://www.creationbaymc.com/?woo_minecraft=check&key=54add0280f7145fab88af9c5cc345da0&names=Pandoroxus

So, I decided to try and post to your server, with the same data that the plugin is using in java:
![](https://i.gyazo.com/e4e14b8d1494e0ef8202cb13b7178a74.png)

Surprisingly, I still get the proper JSON response. So @Pandoroxus could you upload this file to your server, run the `/woo check` command and give me a copy of your log afterwards, this includes some extra debug calls.

[WooMinecraft-1.0.4-RC1.zip](https://github.com/WooMinecraft/WooMinecraft/files/120958/WooMinecraft-1.0.4-RC1.zip)

Additionally, it looks like you're still on the WordPress 1.0.0 version, please use the newest version `1.0.1` it has a hotfix that you need.

**Comment by Pandoroxus** [comment]
@JayWood I'm installing the new one now. The DNS thing shouldn't be an issue now that there's a www there, the points exclusively to the web server, only without the www can it point to both the minecraft and web server.

**Comment by Pandoroxus** [comment]
@JayWood Console output of latest jar:
07.02 15:33:49 [Server] INFO No donations for online users.
07.02 15:33:49 [Server] INFO URL: http://www.creationbaymc.com
07.02 15:33:49 [Server] INFO Key: 54add0280f7145fab88af9c5cc345da0
07.02 15:33:49 [Server] INFO NamesResults: {"success":false,"data":{"msg":"Method or Names parameter was not set.","code":7}}
07.02 15:33:49 [Server] INFO Player List: Pandoroxus

**Comment by JayWood** [comment]
@Pandoroxus okay, I've updated the debug for that NamesResults, which is the result from the WordPress server.  The ONLY reason you should get that code is if all required parameters weren't set.

With this zip I'll be able to tell what is exactly being sent from point a to point b.  https://github.com/WooMinecraft/woominecraft-wp/archive/dev.zip - Delete the other wordpress plugin first.

Once that's done,do the same thing, run `/woo check` in game and give me that output.

**Comment by Pandoroxus** [comment]
@JayWood 
07.02 16:01:24 [Server] INFO No donations for online users.
07.02 16:01:24 [Server] INFO URL: http://www.creationbaymc.com
07.02 16:01:24 [Server] INFO Key: 54add0280f7145fab88af9c5cc345da0
07.02 16:01:24 [Server] INFO NamesResults: {"success":false,"data":{"msg":"Method or Names parameter was not set.","request_data":"{\"woo_minecraft\":\"check\",\"key\":\"54add0280f7145fab88af9c5cc345da0\"}","code":7}}
07.02 16:01:24 [Server] INFO Player List: Pandoroxus

**Comment by JayWood** [comment]
Okay great, that give me a place to start, it looks like the names isn't being posted in the /check request, I'll have to dig into the code and figure that out, especially since it's working for me.

**Comment by JayWood** [comment]
@Pandoroxus One question, if you restart your Minecraft server, then run the command, does it work initially, and then stop working? I had the same issue, but forgot how I fixed it, which is why I ask.

**Comment by Pandoroxus** [comment]
@JayWood I just tested and it just never works.

**Comment by JayWood** [comment]
@Pandoroxus Okay thanks, and I appreciate your patience in this situation. For security reasons go ahead and change your key.  I'll have to dig into the java to figure out why the `names` data isn't being sent to your server from the jar.

I'm not saying this'll be easy to replicate since for me, I'm not having that issue. I'll report back hopefully tonight with a fix, if not after work sometime tomorrow, if I find anything that stands out.

**Comment by JayWood** [comment]
For a technical aspect - @TekkitCommando - the issue seems to be in `Connection.getPlayerResults()` - if you get time to test let me know if you find anything. Could also be with `Connection.processNames()` but I'm not sure at this point, since, well.. it works for me.

**Comment by TekkitCommando** [comment]
I will be testing the plugin hardcore tonight after church but I will look at the code and see if I find anything that look bug prone.

**Comment by TekkitCommando** [comment]
@JayWood My phone screen is tiny and so I may have missed it but I can't find the code that actually gets the players name

**Comment by TekkitCommando** [comment]
I will look again when I'm on my laptop, more then likely I will see it then. I was just scanning really

**Comment by JayWood** [comment]
@TekkitCommando It's in `WooMinecraft.getPlayerList()` - It just returns a comma delimited list of player names.

**Comment by Pandoroxus** [comment]
@JayWood @TekkitCommando Thanks for your help so far, I really appreciate it. I went ahead and changed the key as well.

**Comment by TekkitCommando** [comment]
@Pandoroxus np :) and @JayWood ah ok I see, hmm well I will do some tests when I'm back from church, see if I find something.

**Comment by JayWood** [comment]
@TekkitCommando thanks man, dinner's ready here, and considering I've been coding since noon, it's time to eat :smile: 

@Pandoroxus not a problem, that's why we do this.

**Comment by JayWood** [comment]
@TekkitCommando just checking in, any luck in replicating the issue from @Pandoroxus ?

**Comment by TekkitCommando** [comment]
@JayWood oh sorry, um no, but I am gonna try again today since it's the weekend

**Comment by JayWood** [comment]
@TekkitCommando no updates in 25 days? School maybe?

**Comment by TekkitCommando** [comment]
@JayWood yes :'( I can't wait till May 27th no more school and I can work on my favorite projects like WooMinecraft :D I am sorry for the going MIA as many times as I have this school year, it's the hardest year at my school but summer and next year I will have all the time I need for WooMinecraft sense next year is pretty laid back.

**Comment by JayWood** [comment]
@TekkitCommando Going MIA doesn't bother me, perhaps in the future at least an update once in awhile.  Abandoned tickets is just bad mojo. Also, don't be afraid to say "I don't have the time" or something to that effect.

Personally I've had plenty of time to look further into this, but was under the assumption it was already being looked into.

**Comment by TekkitCommando** [comment]
@JayWood Ok sorry I will make sure to let you know when I am short on time for these things.

**Comment by TekkitCommando** [comment]
And I spelled since wrong in my other message xD

**Comment by JayWood** [comment]
Closing this out as we solved the issue in #79 of the HTTP error by enclosing the URL in the config in double quotes.
