### ISSUE TITLE
Not asking for player ign

### ISSUE THREAD

**Issue by littlemarc2011** [WooMinecraft/WooMinecraft#72]
Well after installing everything... WooMinecraft and WooCommerce I added a product and set a command. When I got to check out it never asks for the player id and asks for shipping details. How do I disable shipping details and have it ask for player ign? Basicly like how it is in: https://youtu.be/vHrxSzo7JnQ?t=4m36s 

Are some of my settings wrong? I setup everything like the wiki said.

**Comment by JayWood** [comment]
No need to open cross-tickets, I responded to the WordPress ticket, closing as this is not java related.
