### ISSUE TITLE
Commands aren't run after purchase, /woo check doesn't work.

### ISSUE THREAD

**Issue by BrightSteel** [WooMinecraft/WooMinecraft#75]
After purchasing a woo commerce product on my website, the Minecraft WooCommerce commands aren't ran. Also, when I run /woo check in-game I'm given "No purchases available - please try again soon".

I have added my key to my wordpress site and setup the config successfully, although the plugin doesn't seem to be communicating with my woo commerce products.

**Comment by BrightSteel** [comment]
Also, when I enter http://pixelhype.net/oo_minecraft=checkey=mykeyhere in my browser, I'm given a 404 error page. I'm not sure if that's supposed to happen or not. (http://pixelhype.net is the website I'm trying to use this plugin for).

Any help would be great. Really need this plugin to work, buycraft is a major rip off!

**Comment by HappyHarm** [comment]
Did you accept/complete the order in the admin panel?

**Comment by JayWood** [comment]
@BrightSteel To chime in here, that url is all screwed up... no wonder it doesn't work.  The correct url structure is like so - http://<mysite>/woo_minecraft=check&key=<key_here>

Notice how woo_minecraft is not missing the `w` and that there's an ampersand `&` between check and key.  Additionally, as @HappyHarm stated, orders must be marked as complete in order for the commands to be prepped for execution on your server.

**Comment by JayWood** [comment]
No comments in 14+ days, closing, feel free to re-open if need be.

**Comment by Drison64** [comment]
Well, when i type `/woo check` it will say in the console `[WooMinecraft] null` can you please help me?. My config: `# Set this to the desired language file you wish to load.
lang: en
update_interval: 60
url: http://dustcraft.eu
key: HIDDEN
debug: true
`
