### ISSUE TITLE
Getting Donations

### ISSUE THREAD

**Issue by morgan2233** [WooMinecraft/WooMinecraft#77]
hello i have installed your plugin but when i buy products of the website in game i dont get them and i have set up using this wiki https://github.com/WooMinecraft/WooMinecraft/wiki but when i buy something i get confirmation but nothing happens in game

**Comment by TekkitCommando** [comment]
Have you set the purchase as complete in your admin dashboard?

**Comment by morgan2233** [comment]
ok it worked when i moved server to my personal mc but it doesn't on my VPS so is there a port or something

**Comment by JayWood** [comment]
@morgan2233 there are no ports, the HTTP request uses standard port 80 to go from your MC Server to the Web Server and back again.

The only thing I can think of is there may be a disconnect somewhere between your MC server and the Web Server.  Which could possibly be a host-related issue ( firewall rules ).

One thing to do, if you have SSH access to your MC server would be to ping the web server address you're using in the WooMinecraft config FROM your MC server via `ping http://yourwebserver.com`

If that succeeds, it means your MC server can successfully talk to your web server.  Next step would be to make sure you can send $_POST data to your web server from the MC server, and that involves a bit of cURL knowledge.

**Comment by morgan2233** [comment]
Thank i did a ping it worked but plugin didnt so then i just tried to test and in the firewall i enabled port 80 and it works
