### ISSUE TITLE
Having issues getting it working.

### ISSUE THREAD

**Issue by Hoki-gcav** [WooMinecraft/WooMinecraft#78]
When I do /woo check it tells me their are no orders after ordering something and pressing order completed.

I have read all the latest issues somewhat relevant to my issue.
I have the wordpress plugin fully setup and updated to its latest version, I'm on the latest wordpress build.
I have the spigot plugin on its latest version and I'm running spigot 1.8.8 with Java 8.
Wordpress is running PHP 5.3.3 if that matters.
The server has port 80 open and I tried pinging the website from my servers SSH - works fine.
When I goto the link http://www.gcav.eu/?woo_minecraft=check&key=fc6b68cd750c4a1b84fa6285f6e79596 (doesn't matter that I left the key in bcos it tells you the key anyway if you get it incorrect lol) The output is `{"success":false,"data":{"success":false,"data":{"msg":"Method or Names parameter was not set.","request_data":"\"Array\"","code":7}}`
Idk what this means, you said before to someone else who had this it was a PHP error, but their issue was the username field wasn't showing and mine is.
Please help, I really don't wana go back to ugly enjin. Its just SO UGLY! ._.

**Comment by mmuziek** [comment]
@Hoki-gcav have you set the key in the config of the plugin and the website to the same key?

**Comment by Hoki-gcav** [comment]
yes

**Comment by FinlayDaG33k** [comment]
I made a pull request to fix the security vulnerability https://github.com/WooMinecraft/woominecraft-wp/pull/15

**Comment by JayWood** [comment]
Simply accessing the site with the key is not enough, at least until WooMinecraft/woominecraft-wp#4 is completed.

Until then, in order to actually see if there are donations you'll need to make sure the name is saved in your database. To do that you need to send data to the URL using a form request, either A. ) Create a simple HTML form to do this for you, or B. ) Use [postman](https://www.getpostman.com/) like I did here for another user: https://github.com/WooMinecraft/WooMinecraft/issues/71#issuecomment-181134371

**Comment by FinlayDaG33k** [comment]
Together with @Hoki-gcav I managed to help him get it to work.
When creating a package, on the wiki it says you only have to check the `virtual` checkbox, while you also have to check the `downloadable` checkbox (or you have to manually complete the order on the order page in the admin panel).

I tested it with my own server as well to verify it, and you have to check the `downloadable` checkbox else it won't work.

**Comment by JayWood** [comment]
@FinlayDaG33k Oh? I've not tested that scenario.  I don't remember making any determinations on product types, that must be an internal WooCommerce thing, but I'll look into that since `downloadable` must be doing something extra in the WC side.

**Comment by FinlayDaG33k** [comment]
Yes, ticking the `downloadable` checkbox makes the order automagically complete.
and for a reason that I don't yet know the orders will only execute after the order status is `completed`

**Comment by JayWood** [comment]
@FinlayDaG33k That's intended, we only want to add commands if an order is completed, otherwise we run the risk of adding multiple commands at different times.

**Comment by JayWood** [comment]
SO if that's the case, this isn't a bug, but a feature of WC whereas if all items on the order are 'downloadable' then it auto-completes said order, which I didn't know.

**Comment by JayWood** [comment]
This issue leads back to this https://github.com/WooMinecraft/woominecraft-wp#i-just-got-a-donation-but-its-not-being-sent - so marking as a duplicate, and not a bug.

**Comment by FinlayDaG33k** [comment]
I always use the `downloadable` checkbox when something is not physical :p makes it easier for me to manage and stuff (which is why I managed to figure it out)

**Comment by JayWood** [comment]
Cool, well thanks for the knowledge - I'll be sure to update the wiki.
