### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by morgan2233** [WooMinecraft/WooMinecraft#81]
Hello

Is there away to so that when they pay it can do a command in a set amount of time so like i buy it 30 days later it does another command so you can set like VIP for 1 mouth

**Comment by JayWood** [comment]
Currently there is no way to do timed commands.  However [PermissionEx](http://dev.bukkit.org/bukkit-plugins/permissionsex/) has that ability, you could setup a ranking system, etc whereas during a certain time frame a user is allowed to play, but afterwards, they're privileges are revoked ( breaking blocks, interacting etc... )
