### ISSUE TITLE
 avoid use / woo check

### ISSUE THREAD

**Issue by Sega0795** [WooMinecraft/WooMinecraft#83]
Hey , look install the plugin and everything works great, but it would be one option to avoid having to use the / woo check

**Comment by JayWood** [comment]
You don't `have` to use woo check, it's actually setup on a timer, I believe 15 minutes is the default?

**Comment by Sega0795** [comment]
Yes, you're right , yesterday I found out and I forget warn him around here, but thanks anyway :)

**Comment by TekkitCommando** [comment]
:+1:
