### ISSUE TITLE
Unknown command ingame while typing command of this plugin.

### ISSUE THREAD

**Issue by ggamehdtv** [WooMinecraft/WooMinecraft#86]
I will get this error while starting the server on 1.8.8 spigot version: http://pastie.org/10872222
I tried it also on a 1.9.2 server and 1.9.4 server but they all aren't working.

When I start the server it says unknown command when doing /woo register

**Comment by TekkitCommando** [comment]
Your Java is too low. Please update to Java 8 or compile the source code for Java 7 if possible.

**Comment by ggamehdtv** [comment]
hmm I will try it asap. Thanks for the fast respond :)

**Comment by TekkitCommando** [comment]
Np :)

**Comment by ggamehdtv** [comment]
It worked! You need to use Java 8 maybe an idea to let it know on the download page of the plugin. So people know it :).

**Comment by TekkitCommando** [comment]
Yeah I will have to do that.
