### ISSUE TITLE
Multiple server support

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/WooMinecraft#87]
Once more bugs are fixed we need to start working on adding support for multiple servers to be added and sending donations to multiple servers.

**Comment by TekkitCommando** [comment]
We technically can do this but it is not possible to send certain commands to one server and different commands to another.

**Comment by JayWood** [comment]
@TekkitCommando I have a solution for this from a commissioned project I'm already working on :)

**Comment by TekkitCommando** [comment]
Awesome :)

**Comment by JayWood** [comment]
Slating this for a later release.
