### ISSUE TITLE
Spigot/Bukkit Site Creds

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#89]
@TekkitCommando I need to get these just in case you're offline for an extended amount of time and need to update the accounts. If you can simply add an email address to it that'll work to so I don't have to have your password?

**Comment by TekkitCommando** [comment]
I got you in the Spigot site. I think I forgot Bukkit, I will do that. I have your real name on Spigot, Isn't it like Phyrax your username? It has been a while since I first met you and I watched that video of the old WooMinecraft on your page for 1.6.4 version.

**Comment by JayWood** [comment]
Correct, my Curse ID is `phyrax` all lowercase. As is my Spigot username.

Could you link both items here ( to the WMC downloads )?

**Comment by TekkitCommando** [comment]
You want me to link the download button to the downloads on Github?

**Comment by JayWood** [comment]
Would make it easier to manage that way? Like link it to the 'latest release' or something?

**Comment by TekkitCommando** [comment]
It's not possible on the Bukkit Page but it is on the Spigot page and it would be easier to manage.

**Comment by TekkitCommando** [comment]
Little off topic but what is WhitelistReport for? You got a server?

**Comment by JayWood** [comment]
Yea http://agedcraft.net it's just a script I built on a whim to output players and when they were last online.

**Comment by JayWood** [comment]
Got tired of typing `/seen <player>`

**Comment by TekkitCommando** [comment]
@JayWood I don't see how you can stand the thing return false and return the command you just typed in chat :P I usually always make the command return true lol

**Comment by TekkitCommando** [comment]
Mind if I apply for this server? :P

**Comment by JayWood** [comment]
It's open to anyone :smile:

**Comment by JayWood** [comment]
By that I mean applications are open lol

**Comment by TekkitCommando** [comment]
@JayWood Lol alright. I will apply. :smile:

**Comment by TekkitCommando** [comment]
@JayWood Is it running Infinity Evolved?

**Comment by TekkitCommando** [comment]
You should put that WhiteList report plugin on Bukkit if you are feeling it. See if you can pick up a few downloads.

**Comment by JayWood** [comment]
Yea it's running infinity evolved, and I had thought about putting that on bukkit/spigot forums

**Comment by TekkitCommando** [comment]
Alright.

**Comment by JayWood** [comment]
@TekkitCommando Any updates on this?

**Comment by TekkitCommando** [comment]
Yeah I added your username to the contributor thing on spigot and i meant to ask you if you had an account on bukkit dev?

**Comment by JayWood** [comment]
@TekkitCommando My name on bukkit is phyrax which is my curse username. But bukkit is so screwed up sometimes.

**Comment by TekkitCommando** [comment]
Yeah I agree xD

**Comment by TekkitCommando** [comment]
You are added to both sites.
