### ISSUE TITLE
WMC Donations?!

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/WooMinecraft#90]
@TekkitCommando this isn't the first time I've been asked this question.  A couple people have wanted to donate to the project in some fashion.

How would you like to handle such a thing? Maybe a page on both our sites which has both our paypal donation bars etc...? As well as links to both sites in the repos?

**Comment by TekkitCommando** [comment]
Yeah we can do that. I am with my family right now but if you want you can send me your PayPal email and I can get both our donation links added to the download pages on bukkit and spigot.

**Comment by TekkitCommando** [comment]
Ok.
