### ISSUE TITLE
Not doing commands ingame while bought a package!

### ISSUE THREAD

**Issue by ggamehdtv** [WooMinecraft/WooMinecraft#91]
Hello,

I installed the plugin on the server (java8) and on wordpress I created the key ingame and copied it to woominecraft in wordpress but when I buy the package I won't get the command which has been added top the product ingame. And there are no errors in the console for this.

Command I use it in the text field: 
![image](https://cloud.githubusercontent.com/assets/19870029/16196705/57e6db68-36ff-11e6-8396-3ae0d3251ced.png)

Can you help me asap to get this work?

**Comment by ggamehdtv** [comment]
@JayWood Which settings do you need exactly

**Comment by JayWood** [comment]
A copy/screenshot of the plugin config from your MC server as well as the username ( exact casing ) of the user who you purchased items for.

**Comment by ggamehdtv** [comment]
@JayWood This is the config of the plugin:
![image](https://cloud.githubusercontent.com/assets/19870029/16208726/da3d0aae-3733-11e6-9172-ed3f771109c8.png)

This is the lang file: 
![image](https://cloud.githubusercontent.com/assets/19870029/16208743/e60eff7c-3733-11e6-868e-d940b32c3f91.png)

Username who purchased the items: ggamehdtv

**Comment by JayWood** [comment]
@ggamehdtv looks like your config got wiped, possibly due to bug #60 - save your key, then delete the config and restart the server and put the key in manually ( by editing the yml file )

**Comment by TekkitCommando** [comment]
@JayWood Why do we have a Dev-Reply tag?

**Comment by JayWood** [comment]
It' actually pointless now that I think about it.  On some trac systems I watch it's used to signify that the task was replied to by a dev, mainly so ppl don't think we're afking on responses.

WMC just isn't large enough to validate the use of such a tag, so we could remove it.

**Comment by ggamehdtv** [comment]
Can you send me a screenshot from a working config so I know how it looks like?

**Comment by JayWood** [comment]
@ggamehdtv 
```
# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "http://playground.dev"

# This must match the WordPress key in your admin panel for WooMinecraft
# For security purposes, you MUST NOT leave this empty.
key: ""

# Set to true in order to toggle debug information
debug: false
```
