### ISSUE TITLE
WooMinecraft Not Showing Up In Wordpress

### ISSUE THREAD

**Issue by FiberSprite** [WooMinecraft/WooMinecraft#94]
Hi, WooMinecraft options will not show up in wordpress after i have put the key in wordpress. Cant seem to figure it out currently and been messing with it for a hour or so.

**Comment by JayWood** [comment]
Make sure the plugin's active first, the latest update changed the function file name which deactivates the plugin.  It's an unfortunate side effect, but had to be done so I can set it up for translations.

If you verify it's active and the options still don't show up, can you elaborate on what you mean by 'options'? I'm a developer so it has a ton of meanings to me :smile: like what screen you're talking about.

**Comment by FiberSprite** [comment]
![image](https://cloud.githubusercontent.com/assets/5142586/16371954/63efbfa0-3c0f-11e6-9786-a66ff44dd32f.png)

**Comment by JayWood** [comment]
Looking at your menu on the left, you seem to not have [WooCommerce](https://wordpress.org/plugins/woocommerce/) installed or setup. It's what this plugin is based upon.

That plugin is what manages your products and commands, not this options page.  This options page is purely for the server key.

**Comment by JayWood** [comment]
Closing, feel free to re-open should the need arise.
