### ISSUE TITLE
/woo check don't works and config bug

### ISSUE THREAD

**Issue by Yaukz** [WooMinecraft/WooMinecraft#96]
Hello,

First of all, sorry for the bad english, it's not my main language.
So, i have a bug. When i type "/woo register", i get my key and then my config resets to this: http://prntscr.com/bnc8xy.
Another bug is that some items take a lot of time to get delivered (like 1 hour or more) or don't even get delivered, because this i think that /woo check is not working.

Some more infos:
- I've followed all the instructions on the plugin wiki page.
- I'm using the latest version of Wordpress, WooCommerce and WooMinecraft.
- I've tried to edit the config with the missing infos after the  /woo register (http://prntscr.com/bnc9vw), without success.
- I'm using MC 1.8.8 (with the compatible Jar).
- Already tried to reduce the "update_interval" to as low as 5, without success too.
- My Woocommerce is installed on a subfolder (mywebsite.com/woocommerce) and the URL is correctly written on the config file.

What should i do?

Thank you! :)

**Comment by JayWood** [comment]
@Yaukz your english is legible, so no worries.

A couple questions: 
* What versions of WMC are you using, both for WordPress and the Minecraft Server? ( The actual version numbers )
* What version of Java are you using?
* Can you provide a full log with `update_interval` set to 5
* Can you provide a full link ( and key ) to your site, as well as a username who actually purchased something?

I'm not entirely sure how 'woocommerce' is a subfolder? WooCommerce is a plugin for WordPress, not a standalone item.  If you have WooCommerce installed properly, you should just enter your website's URL

**Comment by Yaukz** [comment]
Hey,

Versions:
- Wordpress: 4.5.3
- WooMinecraft 1.06 (1.8.8 Jar)
- WooCommerce: 2.6.2

Here's the log with update_interval 5: http://pastebin.com/Nf7mPCQG - In this log, i've received the items that i bough last night, with a 8 hours delay, there's no error on the console...

_Sorry for the misunderstanding, with "WooCommerce installation" i mean my "Wordpress installation"._

Here's the site link with a test packages (stock Wordpress and Woocommerce): "http://absolutecraft.com.br/loja/loja/" (I'm not testing the plugin on my live server, i'm testing it on my Localhost btw. 
Here's my key: "254110f7a7614167af6e901398f4b897". 
Username who purchased something: "Yaukz".

Java Version: Almost sure that i'm using Java 8.

Thanks.

**Comment by JayWood** [comment]
@Yaukz 

Have a look at http://absolutecraft.com.br/loja/loja/?key=254110f7a7614167af6e901398f4b897 notice there are no pending commands.

The delay could be due to WooCommerce not 'completeing' the process until some sort of cron job is ran.

According to WC Documentation 

> WooCommerce by design instantly completes only orders containing "Downloadable" products upon payment. Products that are "only" virtual will have to wait for a manual approval from the shop manager.

Without an order being complete, it's never sent to the feed.

So here's a test for you:

1. Purchase an item for Yakuz again
1. Go to WooCommerce > Orders in the admin
1. Complete the order manually
1. View the link http://absolutecraft.com.br/loja/loja/?key=254110f7a7614167af6e901398f4b897
1. Verify the feed is there.

**Comment by Yaukz** [comment]
Hello,

I already have tried creating a "downloadable package", just for the auto approval, but it takes a lot of time to delivery it too. Already tried to approve it in admin page, takes a while too.

Bough the test package, accepted it on wp-admin and i get this on the key page: "_{"success":true,"data":[]}_".

Something is wrong?

Thanks!

**Comment by JayWood** [comment]
@Yaukz It sounds like the feed cache isn't busting properly, I'm doing some tests and will get back to you shortly.

**Comment by Yaukz** [comment]
Maybe it's something with my webhosting?

**Comment by JayWood** [comment]
The feed is coded to use what's called a 'transient' so basically instead of rebuilding the JSON feed on every request, it caches it for an hour.  This was put in due to large servers with a lot of donations.

However, this transient is meant to be destroyed should an order be saved/updated. If that's not happening that would explain why it's not immediately available.

On the flip side, your host could also be holding onto the transient for longer than necessary.

**Comment by Yaukz** [comment]
Is there a way for me to remove or "destroy" it? And is there a way to "flush" the transient on my host? Thanks!

**Comment by JayWood** [comment]
Yea, there's a plugin called Transient Manager on .org you can use, I use it on other projects to check things like this.

https://wordpress.org/plugins/transients-manager/

The transient name you're looking for will be `wmc-transient-command-feed` once that plugin is installed just go to Tools > Transients and delete that one by it's name.

**Comment by Yaukz** [comment]
Deleting it, the package should arrive? (Sorry, i'm very noob).

**Comment by JayWood** [comment]
No you're fine - once you deleted that transient look at the feed again and your item/command should show up, if it saved properly.

If not, there's not much more i can do without being on your server ( WordPress ) so I can't really troubleshoot much further :disappointed: 

If you're willing to give me access to your test wordpress site that would be tremendously helpful and would speed things up a bit.

You can contact me on skype via my username `jjswebs` or use my contact page here: http://plugish.com/contact-me/
